### ISSUE TITLE
Property Gallery images don't match size settings

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#103]
http://screencast.com/t/s5UtB77oPyE
shortcode - [property_gallery width=640 height=426 image_pan='false']
http://screencast.com/t/fJADudFbIa5k
http://screencast.com/t/KWodOxmel0
http://screencast.com/t/LIFGMPbl5P
https://usabilitydynamics.com/products/wp-property/forum/topic/property-gallery-does-not-work-as-expected/

**Comment by andypotanin** [comment]
So its selecting the wrong image size completely?

**Comment by Mashenka** [comment]
Yes, it resizes images it in some strange logic.

**Comment by theamok** [comment]
WordPress generally does not resize images to non-standard sizes. I'd have
to see the issue in more detail.

Andy Potanin, CEO
Usability Dynamics, Inc.
http://UsabilityDynamics.com http://usabilitydynamics.com/
Direct: 910.742.0111 | Office: 800.270.0781
andy.potanin@usabilitydynamics.com

CONFIDENTIALITY NOTICE

This electronic mail message, including any and/or all attachments, is for
the sole use of the intended recipient(s), and may contain confidential
and/or privileged information, pertaining to business conducted under the
direction and supervision of Usability Dynamics, Inc. All electronic mail
messages, which may have been established as expressed views and/or
opinions (stated either within the electronic mail message or any of its
attachments), are left to the sole responsibility of that of the sender,
and are not necessarily attributed to the sending organization.
Unauthorized interception, review, use, disclosure or distribution of any
such information contained within this electronic mail message and/or its
attachment(s), is (are) strictly prohibited. If you are not the intended
recipient, please contact the sender by replying to this electronic mail
message and delete this message from your system, including any
attachments.

**Comment by Mashenka** [comment]
Functionality of our carousel gallery it seems to me does this.
