### ISSUE TITLE
Property overview images  - functionality changed since  Version: 1.37.6

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#105]
Shows thumbnails of the listed property, however upon clicking the thumbnail it is not showing all of that property’s images. It is showing the next property in the listing.

https://www.usabilitydynamics.com/products/wp-property/forum/topic/porperty-overview-images-lightbox-next-image/
https://www.usabilitydynamics.com/products/wp-property/forum/topic/property-overview-image-link-to-property-single-page/

**Comment by pemaxim** [comment]
it has always showed the only full size of selected image. We have never had fancybox slideshow on overview page. I fixed showing next property's image when fancybox is showed.
