### ISSUE TITLE
Add range drop down  for min and max search fields

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#109]
https://www.usabilitydynamics.com/products/wp-property/forum/topic/price-range-search/

**Comment by pemaxim** [comment]
I think the issue is related to the following suggestion:
http://feedback.usabilitydynamics.com/forums/95259-wp-property/suggestions/3557341-price-min-and-max-select-boxes-instead-of-text-inp

**Comment by pemaxim** [comment]
Done
