### ISSUE TITLE
An error occurred during premium feature check: The API key could not be generated

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#110]
We time to tome receive such claims. 

Credentials leaved in user profile
https://www.usabilitydynamics.com/products/wp-property/forum/topic/premium-features-stopped-working-after-upgrade-from-1-41-4-to-1-42-1/

**Comment by Mashenka** [comment]
One more user 
https://www.usabilitydynamics.com/products/wp-property/forum/topic/error-fetching-premium-add-ons-an-error-occurred-during-premium-feature-check-the-api-key-could-not-be-generated/

**Comment by pemaxim** [comment]
Maria, I need valid ftp ( with correct file permissions! ) and wp-admin credentials to troubleshoot the issue. Thanks!

**Comment by pemaxim** [comment]
I have troubleshooted the issue on client's site and found that it's related to server settings.
Here is some info:
http://screencast.com/t/9OHPqyr3
http://screencast.com/t/iQJp0cnf8

Looks like requests are being blocked by client's host. There could be different things:
- CURL is prohibited
- CACHE issue
- specific IPs blocking
- etc.

Clients have to ask their host providers for help.

P.S.: direct request to our server works fine and returns API key.

**Comment by Mashenka** [comment]
Waiting feedbacks from users.
