### ISSUE TITLE
Add new button in order to delete /update all properties

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#111]

**Comment by andypotanin** [comment]
Update to what? 

v2.0 has a "Refresh" bulk action which automatically "re-saves" each selected listing, therefore revalidating the address, and a few other things that happen on updates only.

![image](https://cloud.githubusercontent.com/assets/1255935/7666604/b69315d2-fbb9-11e4-869d-e8349db65165.png)

Is this what you're asking about too?

**Comment by Mashenka** [comment]
Yes, I meant that. In some cases with child properties if you won't update parent it will show wrong details. So update button will simplify this process.
