### ISSUE TITLE
Warning: Illegal string offset ‘min’ in /home/nyequine/public_html/wp-content/plugins/wp-property/templates/template-functions.php on line 1469

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#115]
Newer versions of PHP don’t like undefined string indexes into an array (among other things). The code should include “if isset($value[[min]) before the existing code. I had to add this before I could continue with my development. I really don’t want to turn off all errors/warnings.
So line 1469 should be

```
<option value='<?php echo (int) $v; ?>' <?php if ( isset($value['min'])) { if( $value[ 'min' ] == $v )  echo " selected='true' ";} ?>>
```

**Comment by andypotanin** [comment]
When there is something like this we need to know which version is used, since line numbers change from one version to the next. In general, though, the v1.0 version of WPP has lots of warnings/notices, I believe they have all been removed in v2.0.

**Comment by Mashenka** [comment]
That warning was on our last version 1.42.2.
