### ISSUE TITLE
XML Import schedule timestamp not updating

### ISSUE THREAD

**Issue by raphaelsuzuki** [wp-property/wp-property#12]
XML Import schedule timestamp (Last import x days/weeks ago.) not updating. The import runs and finishes normally, without errors. This happens with cron importing and manual importing as well.

Tested in 2 different environments.

**Comment by andypotanin** [comment]
Thanks, we're working on XMLI updates at the moment, we'll check it out.

**Comment by raphaelsuzuki** [comment]
Seems to have been fixed in the latest release.
