### ISSUE TITLE
Bug with roles capabilities. Empty fields.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#122]
For example role agent with capabilities to edit and remove his and other properties
and admin only fields Property Type and price
under agent account will look like this
http://screencast.com/t/5DRY5ELo2
so agent see those fields as empty, if he will update property, information will be lost.

at admin account backend looks like
http://screencast.com/t/HtuHHmmvZ

**Comment by pemaxim** [comment]
Does it still is actual issue since we changed the way to manage attributes?
