### ISSUE TITLE
Child properties widget does not consider set order of child properties

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#124]
It sorting them by post_date

**Comment by andypotanin** [comment]
So the menu_order is ignored?

**Comment by Mashenka** [comment]
Menu order is the same as post_date order as I understand.

**Comment by Mashenka** [comment]
no, menu order does no help

**Comment by pemaxim** [comment]
Child Properties widget uses get_posts() function which sorted properties by default:
'orderby'      => 'date',
'order'            => 'DESC'

I added options 'Sort By' and 'Sort Order' to Child Properties widget which will be available in WP-Property 2.1.0 and higher.
