### ISSUE TITLE
Show children Properties setting in Settings/Display tab does not work

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#125]
It showing child properties even if unchecked.

Tested in current and 2.0 version

**Comment by andypotanin** [comment]
No way to enforce it, themes have to honor the setting. We could provide some documentation perhaps on how to check for this in a theme.

**Comment by Mashenka** [comment]
We have option in Display tab and it is didn't work.  - http://screencast.com/t/tDMf9pH6

But now it is working. - http://screencast.com/t/fr14msrmlLy
