### ISSUE TITLE
Hidden attributes are showing

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#126]
If you filled attributes on backend and then choose them to be hidden they will be shown on frontend all the same.

**Comment by andypotanin** [comment]
When exactly are they visible? Or are they not hidden anywhere ever?

**Comment by Mashenka** [comment]
If you hide attribute using hide option in Developer tab they should be visible on backend but not editable and on frondend not visible.
There is also option in order completely hide them from backend in Display tab.

But if you firstly fill them on backend and than choose option in order to hide, they will be shown on frontend all the same.
