### ISSUE TITLE
sq. ft. is hardcoded to be added, if attribute Area has format numeric

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#127]
code in default_api.php

if ( in_array( 'area', $wp_properties[ 'numeric_attributes' ] ) ) {
    add_filter( "wpp_stat_filter_area", 'add_square_foot' );

This should be optional. Probably we need to add such option in Settings/Display tab

**Comment by andypotanin** [comment]
I agree.

**Comment by Mashenka** [comment]
![image](https://user-images.githubusercontent.com/5111163/41852574-3e5345be-7894-11e8-8394-48dedb27e0e7.png)

**Comment by SoSeductive** [comment]
Added new setting
![9e5940eb51](https://user-images.githubusercontent.com/2156026/41859710-6f1584bc-78a5-11e8-8e6c-f5ff4256d3b3.png)
Default value - "sq. ft". If field is empty, on frontend we use default value "sq. ft"
