### ISSUE TITLE
Not closed tag in template-function.php

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#130]
From user:

In template-functions.php under 
wp-property/templates/templates-functions.php 

$wpp_property_results = ''; 

On line 607 there is a tag which is open but not closed. And that breaks 
the HTML validation. 

Here is the code:

$wpp_property_results = '<span class="wpp_property_results">'; 
$wpp_property_results .= ( $properties[ 'total' ] > 0 ? 
WPP_F::format_numeric( $properties[ 'total' ] ) : __( 'None', 'wpp' ) ); 
$wpp_property_results .= __( ' found.', 'wpp' );

It opens a span but does not close it.

So I closed it:

'$wpp_property_results = '<span class="wpp_property_results">'; 
$wpp_property_results .= ( $properties[ 'total' ] > 0 ? 
WPP_F::format_numeric( $properties[ 'total' ] ) : __( 'None', 'wpp' ) ); 
$wpp_property_results .= __( ' found.', 'wpp' ); 
$wpp_property_results .= '</span>';'

**Comment by andypotanin** [comment]
Was this already fixed? I don't see it in v1.0 branch.

**Comment by Mashenka** [comment]
No, still not closed tag - http://screencast.com/t/GKVRGx3QRA
