### ISSUE TITLE
Implement AJAX saving of property settings page.

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-property#134]
The goal of this task is to make the Settings page more user friendly. We can make it much better and more interactive by implementing the features below:

* [x] 1. Pressing the Save button on the Settings page makes an AJAX request to a WP-Property admin-ajax.php action. 
* [ ] 2. If the AJAX request fails, show a notice "We're having trouble saving your settings." and try again infinitely. 
* [x] 3. When AJAX request successfully works and updates the settings for the plugin, show a message saying "Your settings have been updated."
* [x] 4. Add "lock" mode to Settings, similar to the post edit UI. When somebody opens the settings page, and makes a change, make an AJAX request "locking" the settings page. We don't want to lock the settings page until somebody actually makes a change since multiple people may be viewing the settings.
* [x] 5. When the Settings are "locked", show a notice at the top of the page indicating that "[display_name] is currently editing settings."
* [ ] 6. Implement some sort of mechanism to check if settings page becomes locked while somebody is on it.
* [x] 7. All this functionality should only be enabled when `WPP_FEATURE_FLAG_SETTINGS_V2` constant is defined, other feature [flags can be seen here](https://github.com/wp-property/wp-property/blob/latest/wp-property.php#L54). Make `WPP_FEATURE_FLAG_SETTINGS_V2` true by default in the `latest` branch.

**Comment by alimuzzaman** [comment]
@andypotanin 
> 2. and try again infinitely.
What do you mean? Script should keep trying to save settings? If so we should stop after a certain time.
> 6. check if settings page becomes locked while somebody is on it.
Not clear

**Comment by alimuzzaman** [comment]
@andypotanin check here or merge
 https://usabilitydynamics-sandbox-uds-io-develop-alim.c.rabbit.ci/wp-admin/edit.php?post_type=property&page=property_settings

**Comment by Mashenka** [comment]
@alimuzzaman @andy did we add that  to the latest?

**Comment by alimuzzaman** [comment]
@Mashenka Yes, as **Settings Version 2** feature flag.
