### ISSUE TITLE
Traslation Issues

### ISSUE THREAD

**Issue by cmeraz** [wp-property/wp-property#135]
Hello community of wp-property, just downloaded this amazing plugin for a Real State site, been looking around to some features, and i just find that the plugin does not translate the strings i change in the PO files, changed almost every string, but no see reflected on the page, all the wordpress is working in es_ES but just de plugin keeps displaying in the default language.

**Comment by Mashenka** [comment]
Hello.

Other time please use Contact us form for support  - https://www.usabilitydynamics.com/contact-us/

The name of po file witch you translated should be wpp-es_ES.po and it should be put in wp-property/langs folder.

Regards.
