### ISSUE TITLE
Flush Rewrites on Upgrade

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-property#140]
It seems that then Property Settings page must be opened to flush rewrites after upgrading to v2.0.

**Comment by pemaxim** [comment]
Not sure why it's needed. Can you clarify why we should flush rewrites on upgrade? I do not remember anything we could modify so flush rewrites is needed. Anyway, I'm going to add flus rewrites and object cache on activate and deactivate plugin.

**Comment by pemaxim** [comment]
Also I'm going to add flush rewrites and flush object cache on welcome page which is shown on install/upgrade

**Comment by pemaxim** [comment]
Done.
