### ISSUE TITLE
Address Label Can Not be Renamed

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-property#143]
![image](https://cloud.githubusercontent.com/assets/1255935/8146986/7cf434be-1225-11e5-8ba5-3285189c40b3.png)

**Comment by Mashenka** [comment]
And Price attribute

**Comment by Mashenka** [comment]
Deposit, Area and Phone Number also

**Comment by antonkorotkov** [comment]
Not sure why but it was done intentionally by  `$d = !$this->get( 'property_stats', false );` that was returning `false` if something found. That's why it was updating attributes with standard ones every time.
Changing to `$d = $this->get( 'property_stats', false );` fixes the issue.

**Comment by antonkorotkov** [comment]
Fixed
