### ISSUE TITLE
Add ability to sort(move) property types in Developer tab

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#144]
Like this can be done with attributes in Settings/Developer tab

![image](https://cloud.githubusercontent.com/assets/5111163/17015493/1bf250fa-4f33-11e6-8bc4-25f3cf4a26c5.png)

**Comment by raj-uimatic** [comment]
![screenshot_8](https://cloud.githubusercontent.com/assets/5083106/17056792/73252cca-5033-11e6-8661-46338ef11adb.png)
