### ISSUE TITLE
Importing fails to download images on site protected by htpasswd

### ISSUE THREAD

**Issue by garretthyder** [wp-property/wp-property#150]
Hello,

I opened a support topic concerning this but might be best handled as a git issue.
Support Topic - https://wordpress.org/support/topic/import-fails-to-download-images-when-behind-htpasswd?replies=1#post-7153347

Basically Image Downloads fail during import due to htpasswd blocking the spawned url threads which trigger the process to download.

Feature Request: Please provide options for users to supply htpasswd credentials that can be used for the generation of the import thread urls so they don't hit the wall and can properly process image downloads.

Thanks

**Comment by Mashenka** [comment]
Hello.

Thank you for pointing. I will move this task to importer private project.

Regards.

**Comment by garretthyder** [comment]
Thanks @Mashenka

**Comment by kaiocesar** [comment]
Hi there, 
I've had the same problem here. I'm trying to import some data from STAGE environment to PRODUCTION, but the STAGE env has HTPASSWD protection and I can't remove this one. So, how can I set it from the WordPress importer plugin?

**Comment by Mashenka** [comment]
Hello.

There is no way to set up that right now. We could implement that for you as custom service, order customization you could here - https://app.hubspot.com/meetings/marcus-smoot

Regards.
