### ISSUE TITLE
Add Chinese address localization 

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#162]
traditional Chinese which refer to 'zh_TW'.
http://screencast.com/t/JULXWXmG

ticket - https://usabilitydynamics.uservoice.com/admin/tickets/4169?tracking_code=fbc79958090d6cd5b518f81a47e83ce8

**Comment by pemaxim** [comment]
Added.
But, be aware, user can add any custom language via "wpp_google_maps_localizations" filter.

For example:

`
add_filter( "wpp_google_maps_localizations", function( $data ) {
  $data[ 'zh-TW' ] = 'Chinese';
  return $data;
} );
`
