### ISSUE TITLE
Add ability to disable Fancybox on Front End pages

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#165]
Related support topic: https://wordpress.org/support/topic/use-themes-default-fancyboxlightbox

**Comment by SoSeductive** [comment]
@Mashenka Done. Please test in on workspace
https://workspace.uds.io/properties/property-rancocas-road-elbow-lane-burlington-nj-08016-usa/

**Comment by SoSeductive** [comment]
@Mashenka Option added in Settings / Main tab
