### ISSUE TITLE
Get rid of inline js (pagination) in property_overview shortcode

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#171]

**Comment by SoSeductive** [comment]
@Mashenka Here we have only one usage, and this script depends on php. I think it not need to do
![a355e271e8](https://user-images.githubusercontent.com/2156026/42095813-5e59121e-7bbc-11e8-9d6f-7e5fc7764d9c.png)

**Comment by Mashenka** [comment]
ok, closing it
