### ISSUE TITLE
Property Meta widget

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#174]
do not show attributes with empty values - http://screencast.com/t/06YwmL3XWpB

issue on the site  - http://workspace.uds.io/properties/1588-watersedge-rd-2/
I have used Property Meta widget in Buildings - Right sidebar widget area
http://workspace.uds.io/wp-admin/widgets.php

**Comment by Mashenka** [comment]
Hide also widget if there is nothing to show, so there should't be blank space or blank div

**Comment by Mashenka** [comment]
Hide also widget if there is nothing to show, so there should't be blank space or blank div

**Comment by alimuzzaman** [comment]
I did that.

**Comment by Mashenka** [comment]
Ok. See. I'm closing this task.

**Comment by alimuzzaman** [comment]
Time to complete  #192+#182+#174 is 2:50 min
