### ISSUE TITLE
Fred Validate and format attributes values on saving them to Database

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#177]
Validate and format attributes values on saving them to Database to prevent the following issues in future: https://wordpress.org/support/topic/sort-by-price-giving-incorrect-results-1?replies=5

**Comment by pemaxim** [comment]
The current issue is mostly duplicated. See: https://github.com/wp-property/wp-property/issues/199

**Comment by andypotanin** [comment]
@pemaxim closing this in lieu of the new Elasticsearch integration.
