### ISSUE TITLE
Add numeric pagination for Property Overview shortcode/widget

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#179]
Add ability to switch from 'slider' to  'numeric' pagination

**Comment by Mashenka** [comment]
One of the user share his code:

Wp-property\lib\template-functions.php

Line 445 added

`$('[class^="custom_page_"]').removeClass('pagination_active');`

`$('.custom_page_' + this_page).addClass('pagination_active');`

Line 666 added and replaced

`<?php if ( !empty( $use_pagination ) ) { ?>`

`<div class="wpp_pagination_slider_wrapper">`

`<div class="wpp_pagination_back wpp_pagination_button"><?php _e( 'Prev', 'wpp' ); ?></div>`

`<?php for ($i = 1; $i <= $pages; $i++) { ?>`

`<div class="custom_page_<?php echo $i; ?>">`

`<a><?php echo $i; ?></a>`

`<script type="text/javascript">`

`(function ($) {`

`$('.custom_page_<?php echo $i; ?>').on('click', function (e) {`

`e.preventDefault();`

`wpp_do_ajax_pagination_<?php echo $unique_hash; ?>(<?php echo $i; ?>)`

`});`

`})(jQuery);`

`</script>`

`</div>`

`<?php } ?>`

`<div class="wpp_pagination_forward wpp_pagination_button"><?php _e( 'Next', 'wpp' ); ?></div>`

`<div class="wpp_pagination_slider"></div>`

`</div>`

`<?php } ?>`

Then I added .pagination_active to wp-property/static/styles/wp_properties.css and hid the .wpp_ui .wpp_pagination_slider.ui-slider-horizontal on line 545.`

https://usabilitydynamics.uservoice.com/admin/tickets/5505?tracking_code=27b28e1769f4f429c31f62917bd5d969

**Comment by pemaxim** [comment]
@Mashenka we already have 'ready' solution.  
Also, we are going to do the following 'pagination' refactoring and improvements:
- [x] move pagination logic directly to property_overview shortcode's class.
- [x] move javascript from HTML source to separate files
- [x] implement numeric pagination
- [x] add attribute 'pagination_type' with values 'slider' and 'numeric'.
- [x] add option on Settings page: 'Select default pagination type for all [property_overview] shortcodes'. Already existing users on upgrade will have enabled 'slider' ( legacy pagination type ) to prevent conflicts. New installation will have enabled 'numeric' pagination by default.
- [x] load html, javascript file, css styles depending on particular pagination type.
- [x] set 'numeric' pagination by default for new WPP installations

**Comment by pemaxim** [comment]
Done
