### ISSUE TITLE
Child properties inherit issue

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#180]
parent - http://screencast.com/t/IdNaD6j3
settings - http://screencast.com/t/g7f1qhhjq5gl
child - http://screencast.com/t/UYC7M5dqnRxh

On the site, the name of the attribute Security Deposit
parent property - http://workspace.uds.io/wp-admin/post.php?post=3972&action=edit
child property - http://workspace.uds.io/wp-admin/post.php?post=3486&action=edit

**Comment by alimuzzaman** [comment]
Previously inherit worked with only text box. Now it will work with any form item.

**Comment by Mashenka** [comment]
- [ ] Fix also frontend view
  parent property - 

http://workspace.uds.io/properties/1588-watersedge-rd-2/

child property

http://workspace.uds.io/properties/1588-watersedge-rd-2/798-burnhamthorpe-rd-e/

**Comment by Mashenka** [comment]
Also about other field types
- [ ] Single checkbox(this can be changed in developer tab)
  ![image](https://cloud.githubusercontent.com/assets/5111163/11337725/23e00514-9200-11e5-88af-3cf3b92edffd.png)

on parent property shows correctly
on child property it will looks like this
![image](https://cloud.githubusercontent.com/assets/5111163/11337780/a5d6e24a-9200-11e5-9475-54c2af313c5e.png)
 and on frontend won't be showed at all - 
![image](https://cloud.githubusercontent.com/assets/5111163/11337790/be4171b0-9200-11e5-93d6-4fd281a63378.png)

**Comment by Mashenka** [comment]
- [x]  Dropdown Selection field type issue

parent property shows correctly
child property do not have this attribute on frontend at all
![image](https://cloud.githubusercontent.com/assets/5111163/11337886/8cc93f40-9201-11e5-9c92-8b96da3c231b.png)

**Comment by alimuzzaman** [comment]
I was missed frontend  totally.

**Comment by Mashenka** [comment]
Check all other field types also:
![image](https://cloud.githubusercontent.com/assets/5111163/11337975/2ccfc0fe-9202-11e5-90d1-30f67f98f9cf.png)

**Comment by alimuzzaman** [comment]
Check it.

**Comment by Mashenka** [comment]
Frontend still have issues.
This is parent property look with multicheckbox type. There should be 2
![image](https://cloud.githubusercontent.com/assets/5111163/11365025/e73ed15c-92b4-11e5-8d72-049a4a43adf5.png)
backend
![image](https://cloud.githubusercontent.com/assets/5111163/11365188/c76fe93c-92b5-11e5-88c1-a61d2b8c76f1.png)

http://workspace.uds.io/properties/1588-watersedge-rd-2/

**Comment by alimuzzaman** [comment]
At this point there is no way to happen that. Maybe that happened for any bug.

**Comment by alimuzzaman** [comment]
Got it. Only way to happen that is, when you change the field type.
When you change it to any single type, then it updates all the 3 saved value as 2.

**Comment by Mashenka** [comment]
Sorry to confuse you. The correct way showing on frontend multicheckbox attributes is showing their values separated by comma. The view of child property attributes should be the same as it's parent.

At the moment it shows 2,2,2 on parent property, but should be 2
and on child property should be 2

**Comment by alimuzzaman** [comment]
That problem will fix when you unset all value then save. After that all value will be clear. Then you can set value again.

**Comment by Mashenka** [comment]
Ok. See. I will check also the rest of field types and let you know

**Comment by Mashenka** [comment]
with multicheckbox field type can you make on backend of child property also as checkbox
now it looks like text field
![image](https://cloud.githubusercontent.com/assets/5111163/11375416/543db25a-92ec-11e5-9823-16b5f90fd832.png)

**Comment by alimuzzaman** [comment]
![settings rent home wordpress](https://cloud.githubusercontent.com/assets/6744156/11375547/12ece0d6-9306-11e5-8f31-11094d336a38.png)

**Comment by Mashenka** [comment]
I'm sorry. That was a typo. With Single check box

**Comment by Mashenka** [comment]
with singlecheckbox field type can you make on backend of child property also as checkbox
now it looks like text field
![image](https://cloud.githubusercontent.com/assets/5111163/11375416/543db25a-92ec-11e5-9823-16b5f90fd832.png)

**Comment by alimuzzaman** [comment]
Time to complete #180 :: 3:0 min + 1:40 min
Maybe some time from others issue included here.

**Comment by Mashenka** [comment]
Did you check all the field types?

E.g Currency,Number, URL, OEmbed, Date and Time Picker and ALL other Data entry shows wrong text on child property
![image](https://cloud.githubusercontent.com/assets/5111163/11422085/26d7d08e-944a-11e5-9c2e-7b8722513959.png)

![image](https://cloud.githubusercontent.com/assets/5111163/11422180/f0b230d4-944a-11e5-9cdc-b7da92855b69.png)

frontend of child property also wrong

**Comment by alimuzzaman** [comment]
Yes I have checked all type.

**Comment by Mashenka** [comment]
It seems that not. Data picker, Date and time picker and time picker are not inheriting from parent
Check with the attribute Tracking Phone Number
parent http://workspace.uds.io/wp-admin/post.php?post=3954&action=edit
child http://workspace.uds.io/wp-admin/post.php?post=3489&action=edit

Color picker are editable on child property and can be changed

**Comment by Mashenka** [comment]
Image Upload, File Upload, File URL also have issue:
- Have strange white box on both child and parent property
  ![image](https://cloud.githubusercontent.com/assets/5111163/11471164/50ac63c0-9774-11e5-9fc7-407ff3135f63.png)
  - Editable on child property
  - Images and file upload not showing on frontend

**Comment by alimuzzaman** [comment]
That's because there are saved value from previous field type what do not match with current one.
To disable image upload & file upload I need to put some jquery code, where can I put them?

**Comment by alimuzzaman** [comment]
To solve that blank image issue I need to customize/override class "RWMB_Image_Advanced_Field" and 'RWMB_File_Advanced_Field" from Custom Field plugin.
Or we can have those field with new name?
Also a custom copy will be needed for inherited fields.

**Comment by pemaxim** [comment]
@alimuzzaman as I mentioned before, we must not override/customize anything in third-party libraries and plugins. I would suggest you to:
- Modify RWMB_Wpp_Inherited_Field class
- OR create new custom field class. Something like RWMB_Wpp_Inherited_Images_Field.

Look through RWMB_Wpp_Inherited_Address_Field class usage for example.
See, how it's being used in `/lib/classes/class-meta-box.php`

![image](https://cloud.githubusercontent.com/assets/308489/11501019/9bd71fbe-9839-11e5-9620-a87293e8e25e.png)

So you could do something similar with Inherited Images field.

**Comment by alimuzzaman** [comment]
This is what I need.

**Comment by alimuzzaman** [comment]
I wasn't saw any issue on File url field.

**Comment by Mashenka** [comment]
on child property error and nothing on frontend
![image](https://cloud.githubusercontent.com/assets/5111163/11566855/4e7cfc80-99f5-11e5-8e42-02698e408e88.png)

parent - http://workspace.uds.io/wp-admin/post.php?post=7227&action=edit&lang=en 
child - http://workspace.uds.io/wp-admin/post.php?post=7224&action=edit&lang=en

Also I thought you showed another view of images
![image](https://cloud.githubusercontent.com/assets/5111163/11566929/a3d37376-99f5-11e5-8d58-fe5bf23f185f.png)

**Comment by alimuzzaman** [comment]
Time : 3:00 + 1:40 + 7:40

**Comment by Mashenka** [comment]
now child property do not show values on backend
![image](https://cloud.githubusercontent.com/assets/5111163/11658373/5751e5dc-9dd3-11e5-943b-9935b271f7cf.png)

and also you didn't fix the view of image,it still shows numbers instead of image
![image](https://cloud.githubusercontent.com/assets/5111163/11658436/9f14cf60-9dd3-11e5-94dc-059ae743e2ea.png)

parent http://workspace.uds.io/wp-admin/post.php?post=8109&action=edit&lang=en
child http://workspace.uds.io/wp-admin/post.php?post=8103&action=edit&lang=en

**Comment by Mashenka** [comment]
image still showing as numbers on child and parent property. Did you check that?

**Comment by alimuzzaman** [comment]
For
Img 1. I was removed important line with others so that errors occurred.
Img2. I see image instead of number.

**Comment by Mashenka** [comment]
you see image on workspace or locally?

**Comment by alimuzzaman** [comment]
Both

**Comment by Mashenka** [comment]
Files Upload attribute missed on frontend for some reason

**Comment by alimuzzaman** [comment]
1.  about wp-property-feps.
   if that's found Property Attributes with slug "image_upload" then it make the input_type & data_input_type "image_upload". I didn't found  any attribute type "image_upload". The existing one is "image_advance". This was causing image to show ID.
2. $property_object->property_type in function get_stat_values_and_labels() called by draw_stats return The property type label not key. Is that normal. Maybe changed in few days ago. I wasn't have up to date version of work-space. So it was worked on my local.

**Comment by alimuzzaman** [comment]
Title of the issue should be changed. Because it's no longer only about multi-checkbox.

**Comment by Mashenka** [comment]
The issue is fixed. I'm closing it.
Just want to make sure about your question

> $property_object->property_type in function get_stat_values_and_labels() called by draw_stats return The property type label not key. Is that normal?

Can you clarify please.

**Comment by pemaxim** [comment]
@alimuzzaman https://github.com/wp-property/wp-property/commit/e44123accc8c7067a839eafb47478e95b0e28c3a#commitcomment-14898856

**Comment by pemaxim** [comment]
> about wp-property-feps.
> if that's found Property Attributes with slug "image_upload" then it make the input_type & data_input_type "image_upload". I didn't found  any attribute type "image_upload". The existing one is "image_advance”.

We have ‘image_advanced’ only. Why are you asking about 'WP-Property: FEPS’? Are you working on FEPS? 

> $property_object->property_type in function get_stat_values_and_labels() called by draw_stats return The property type label not key. Is that normal.
> Maybe changed in few days ago.

Object should contain the following properties:
property_type. It contains slug of particular property_type
property_type_label. It contains label of particular property_type.
I’m not sure what is your question about. Please, clarify.

**Comment by pemaxim** [comment]
I believe it was written a long time ago. But I may be wrong. Anyway, the code is included to current WP-Property 2.1.4 release which was launched 26 November
See: http://plugins.svn.wordpress.org/wp-property/tags/2.1.4/lib/class_functions.php 
What is wrong with it?

**Comment by pemaxim** [comment]
> I didn't found  any attribute type "image_upload". The existing one is "image_advance”.

I believe you are confused. Postmeta keys are not the same as Attribute Types.
For example, you have Price attribute, which has currency type, but ‘price’ slug. So, you can get value of attribute via $property->price
image_advanced and file_advanced are two unique attributes types which are storing values under ‘image_upload’ and ‘file_upload' meta keys instead of attribute’s slug. So, e.g., to get value, you should look at $property->image_upload. 
It happens, because Attribute Types management is based on Meta Box plugin which handles attributes management on Edit Property page.(edited)

I think it can cause different issues in future. So, probably, we should create our custom image_advanced and file_advanced fields which will be based on native ones, but use attribute slugs for storing data instead of defined ‘image_upload’ and ‘file_upload'

I will create another issue for it.

**Comment by alimuzzaman** [comment]
I apologize to not replay. How I missed!
@pemaxim 
[As your question](https://github.com/wp-property/wp-property/issues/180#issuecomment-163601914)
1. I am not working on feps. I commented [here](https://github.com/wp-property/wp-property/commit/e44123accc8c7067a839eafb47478e95b0e28c3a#commitcomment-15168357).
2. I was got label for property_type instead of slug on class_function.php:3498 
$property_object partial.

``` php
    [property_type] => Building
    [property_type_label] => Building
    [wpp::google_validation_status] => success
    [wpp_gpid] => gpid_1303119028
    [display_address] =>
```

Abut your last [comment](https://github.com/wp-property/wp-property/issues/180#issuecomment-163602271)
3. We talked and there is no confusion now (we both was confused).
