### ISSUE TITLE
Adding Slashes if attribute or property type contain apostrophe

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#181]
approximately that was changed after 1.42.2 
e.g Mortgagee's

https://usabilitydynamics.uservoice.com/admin/tickets/5415/?q=assignee%3Ame+status%3Aopen

**Comment by alimuzzaman** [comment]
need more clarification

**Comment by Mashenka** [comment]
Try to add property type with apostrophe e.g Mortgagee's it will change it to e.g Mortgagee/s and after each update of the page it will add additional slash like this e.g Mortgagee///s
