### ISSUE TITLE
Property Attributes, Property Term  widget - shouldn't show the title of widget if no attributes exist for property

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#182]
http://screencast.com/t/t4lNqiajPPwe

Issue on the site. - http://workspace.uds.io/properties/1588-watersedge-rd/
I have used widget Property Attributes in the widget area Buildings -Right Sidebar - http://workspace.uds.io/wp-admin/widgets.php

**Comment by Mashenka** [comment]
Check also Property Terms widget with the same issue - http://workspace.uds.io/properties/1588-watersedge-rd-2/

**Comment by Mashenka** [comment]
Hide also widget if there is nothing to show, so there should't be blank space or blank div

**Comment by alimuzzaman** [comment]
Time to complete  #192+#182+#174 is 2:50 min
