### ISSUE TITLE
 SyntaxError on property overview

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#192]
[property_overview property_type=building per_page=100] the amount of buildings should be less than 100

issue on the site - http://workspace.uds.io/properties/
(use FireBug to see error)

 SyntaxError:
![image](https://cloud.githubusercontent.com/assets/1255935/11300272/e59c4372-8f8d-11e5-803f-413215cc3e14.png)

parameter use pagination is empty:
![image](https://cloud.githubusercontent.com/assets/1255935/11300276/f0a38050-8f8d-11e5-91e6-3fc818cbe3ac.png)

**Comment by Mashenka** [comment]
@uderic  why do you think this is not high priority issue?

**Comment by uderic** [comment]
High priority is fine. Just cleaning up labels. I'll review with you shortly.

**Comment by alimuzzaman** [comment]
In which file that javascript is located?

**Comment by pemaxim** [comment]
To troubleshoot the issue you have to setup WorkSpace on local server.
@alimuzzaman: do you need db backup? do you have access to WS ( WorkSpace ) repo?

**Comment by alimuzzaman** [comment]
> per_page=100 
> Maximum will 100, what will be happen if user give larger than 100?

**Comment by andypotanin** [comment]
@pemaxim workspace is setup for alim and I've given him DB dump as well. 
@alimuzzaman do you have any more questions about this? My understanding is that when "per_page" is over 100 but there aren't enough listings then some JS error occurs.
