### ISSUE TITLE
XMLI. Accents in the titles do not generated correctly in the feed

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#193]
property with accents- http://workspace.uds.io/wp-admin/post.php?post=3954&action=edit
schedule - http://workspace.uds.io/wp-admin/edit.php?post_type=property&page=wpp_property_import#1448018348
imported property - http://workspace.uds.io/wp-admin/post.php?post=3975&action=edit

You can take xml feed here in properties/Settings/Help tab- http://screencast.com/t/Yzu1aENI

**Comment by Mashenka** [comment]
This is note for me.

Tickets which should be updated after fix- https://usabilitydynamics.uservoice.com/admin/tickets/5651?tracking_code=3558d64ec605f7a407b79cb5579c4d4b

https://usabilitydynamics.uservoice.com/admin/tickets/5941/?q=assignee%3Ame+status%3Aopen

**Comment by alimuzzaman** [comment]
Time to complete #193 is 1:20 min
