### ISSUE TITLE
[property_meta] and [property_attribute] add parameter show_taxonomy_label=true/false

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#205]
At the moment it shows only value

reference to our shortcodes and it's parameters here - https://www.usabilitydynamics.com/product/wp-property#documentation=wp-property-help/wp-property-shortcode-cheat-sheet

**Comment by raj-uimatic** [comment]
![screenshot_9](https://cloud.githubusercontent.com/assets/5083106/17056831/bc566d8c-5033-11e6-9411-fc4d0b6a31bc.png)
