### ISSUE TITLE
Permalink on edit single property page goes on backend

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#209]
so it just refreshes the page. It should go to frontend
![image](https://cloud.githubusercontent.com/assets/5111163/12003896/49e5fe24-ab43-11e5-9e3b-89ba0af643c6.png)

**Comment by alimuzzaman** [comment]
Need help with this. I have tried but not get how it's working.
@pemaxim

**Comment by Mashenka** [comment]
was fixed by Boris
