### ISSUE TITLE
Text Editor field type add odd </br>

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#212]
to show line break you will need to put the text in the following way:

text &lt;/br&gt; text2 &lt;/br&gt;

if you will write as following it will put double br
text &lt;/br&gt;
text2 &lt;/br&gt;

**Comment by alimuzzaman** [comment]
`"</br>"` what do you mean? `<br>` `<br />`
That's invalid

**Comment by Mashenka** [comment]
steps to replicate:
1. Use Text Editor Data Entry field
2. Fill it in some property with several lines of text
3. Save property
3. You will see extra br in text (you will need to update the page cuase it not showing when just switching between visual and text)
![image](https://cloud.githubusercontent.com/assets/5111163/13005202/5499eb5e-d191-11e5-8a49-3cfd7059f639.png)

![image](https://cloud.githubusercontent.com/assets/5111163/13005215/6274467a-d191-11e5-9833-6eb28ec1acc1.png)

https://workspace.uds.io/wp-admin/post.php?post=9149&action=edit&lang=en

**Comment by alimuzzaman** [comment]
The nl2br() function in [template-function.php:312](https://github.com/wp-property/wp-property/blob/latest/lib/template-functions.php#L312) causing the problem.
Should I add logic to ignore only for texteditor or remove that?

**Comment by Mashenka** [comment]
Yes, add logic to ignore only for texteditor
