### ISSUE TITLE
Multi-check box field searching only within first checked value

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#214]
It will show properties only from 1 area on released wp-property version
![image](https://cloud.githubusercontent.com/assets/5111163/12455509/0ccb79dc-bfad-11e5-9e27-b4799061abe7.png)

and won't show any property on wprkspace
https://workspace.uds.io/properties/106-buckingham-rd-north-allegheny-15238-pending-image-downloads/

User to notify about the fix  - https://usabilitydynamics.uservoice.com/admin/tickets/6973?tracking_code=e412e62b9b5e34a0921d7d3135f8df1c

**Comment by alimuzzaman** [comment]
it's also working great. Please check again now.
Maybe was issue with importer 33

**Comment by Mashenka** [comment]
Yes, it is working now. But this is not working on released version of wp-property(you can check locally) and I need to send the fix to the user.

**Comment by alimuzzaman** [comment]
@Mashenka it's work locally with released version.

**Comment by Mashenka** [comment]
ok. I will check again

**Comment by Mashenka** [comment]
I need to see that on your local site. Or I will show you my site. Need a call

**Comment by alimuzzaman** [comment]
@Mashenka What was the last situation(sorry forgot).

**Comment by Mashenka** [comment]
Let's keep it not closed. I will check one more time before release

**Comment by Mashenka** [comment]
I have replicated the issue on workspace.

This is working when only numbers in the list, like 1,2,3
but when there exist come symbols like 1 area, 2 area, 3 area that won't work

You can check with security deposit on this property search. I have added 1 property for first and second value
https://workspace.uds.io/property/barrie/
