### ISSUE TITLE
WPML Compatibility: Property form translation

### ISSUE THREAD

**Issue by srdjan-jcc** [wp-property/wp-property#216]
![spanish property form es wp property 2016-01-27 12-42-47](https://cloud.githubusercontent.com/assets/3109112/12653703/0071ac98-c5f1-11e5-9bd6-309c6eba9f96.png)

Attributes not translated
(including custom fields, dropdown options)

http://pluginwpproperty.compatibility.wpml.org/property-form/?lang=es
http://pluginwpproperty.compatibility.wpml.org/wp-admin/edit.php?post_type=property&page=page_feps

**Comment by Mashenka** [comment]
Moved to the appropriate repository
