### ISSUE TITLE
WPML Compatibility: Frontend and agent template Properties pagination and filtering

### ISSUE THREAD

**Issue by srdjan-jcc** [wp-property/wp-property#218]
Using Property list pagination or filtering returns results in default language.

http://pluginwpproperty.compatibility.wpml.org/properties?lang=es
http://pluginwpproperty.compatibility.wpml.org/agent-page/?lang=es

![spanish agent page es wp property 2016-01-27 12-48-12](https://cloud.githubusercontent.com/assets/3109112/12749291/e2dc1570-c9af-11e5-85fb-131836f7242e.png)
![spanish properties es wp property 2016-01-27 12-37-03](https://cloud.githubusercontent.com/assets/3109112/12749292/e2e51e86-c9af-11e5-8e3d-a1f5844534ee.png)

**Comment by Mashenka** [comment]
that was fixed in 2.3.0
