### ISSUE TITLE
WPML Compatibility: Agent info cannot be translated 

### ISSUE THREAD

**Issue by srdjan-jcc** [wp-property/wp-property#219]
How to translate additional info about agent?

http://pluginwpproperty.compatibility.wpml.org/agent-page/?lang=es
http://pluginwpproperty.compatibility.wpml.org/wp-admin/edit.php?post_type=property&page=show_agents&user_id=1045&action=edit

![real estate agents wp property wordpress 2016-01-27 12-54-41](https://cloud.githubusercontent.com/assets/3109112/12749341/43fe8086-c9b0-11e5-96ba-029b6f6a9ebf.png)
![spanish agent page es wp property 2016-01-27 12-53-31](https://cloud.githubusercontent.com/assets/3109112/12749342/440168c8-c9b0-11e5-86ca-2a31fc16e852.png)

**Comment by Mashenka** [comment]
Moved to agents repository
