### ISSUE TITLE
add-ons screen styling issue with icons

### ISSUE THREAD

**Issue by ewsopp** [wp-property/wp-property#222]
The icon sizes for each add-on don't appear to be restricted to a set width or height. 

![2016-02-09_13-16-07](https://cloud.githubusercontent.com/assets/5578537/12926031/621bf1a0-cf2f-11e5-9e8d-147b1251f62f.jpg)

**Comment by Mashenka** [comment]
That should be fixed in last release - https://github.com/wp-property/wp-property/commit/688dfa20c4c5ea3b738739a0e172902c6469a5da

Did you update wp-property already?
