### ISSUE TITLE
Single checkbox became enabled when publishing new property

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#223]
To resolve the issue I modified the class-wpp-checkbox.php file on line 22 replacing;
checked( ! empty( $meta ), 1, false ), // from original class of checkbox
WITH
checked( $meta, 'true', false ), // from original class of checkbox
which is the original code.

See original message here

https://wordpress.org/support/topic/checkboxes-stay-checked-always-issue-introduced-in-215?replies=1

**Comment by alimuzzaman** [comment]
@pemaxim I need to add filter for checkbox, where I should put it?
The filter is on wpp importer
https://github.com/wp-property/wp-property-importer/blob/v5.0/lib/class-wpp-property-import.php#L2790

**Comment by Mashenka** [comment]
Issue fixed

**Comment by Mashenka** [comment]
@antonkorotkov review please. We need to do release
