### ISSUE TITLE
Can not save new Property Types

### ISSUE THREAD

**Issue by rkarpuzov** [wp-property/wp-property#225]
In Property -> Settings -> Property Types I try to add new types, but nothing happens when click Save Changes. Wordpress - some versions including latest official, wp-property: 2.1.5

**Comment by Mashenka** [comment]
Hello.

WP-Property do not have mentioned issue. Try to disable all third party plugins one by one to investigate the issue.
Also use support in future. - https://www.usabilitydynamics.com/contact-us

Regards.

**Comment by rkarpuzov** [comment]
no any 3th party plugins :(  

```
On Tuesday, February 23, 2016 2:50 PM, Maria Kravchenko <notifications@github.com> wrote:
```

 Hello.WP-Property do not have mentioned issue. Try to disable all third party plugins one by one to investigate the issue.
Also use support in future. - https://www.usabilitydynamics.com/contact-usRegards.—

**Comment by Mashenka** [comment]
As I mentioned before, contact support for further investigation.

Thanks
