### ISSUE TITLE
Get started page! Set up Assistant

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#235]
The steps needed to setup WP-Property on a new site are confusing - there are a lot of settings that need to be configured and our default settings were initially targeted towards "property management" not "real estate". Upon installation of WP-Property on a new site the setup wizard will be shown allowing people to quickly configure settings that otherwise would take a while. 

We need to create a step-by-step set up wizard for quick set up WP-Property plugin on first install. Majority of people who install WP-Property should be able to have a presentable site within several minutes, if not less, after going through an interactive wizard.

The slides we envision are:
- Welcome to WP-Property. (very brief, don't need a bunch of text that nobody wants to read right away)
- Select the Property Types you want to list. (Homes, Offices, Apartments, etc.)
- Select what you want the single property pages to look like. (Show few design concepts, sidebar on left vs sidebar on right type of layouts, perhaps 3-4)
- Ask user if they'd like for us to import 10 sample properties (for each property type they selected). It should be clear that they can delete these later.
- etc. (see Google Doc below for wireframe)

**Comment by Mashenka** [comment]
Old design concept: https://projects.invisionapp.com/d/main#/console/2819220/62989748/preview

New setup wizard: https://docs.google.com/presentation/d/1ujx9QRm_8B0vzaC3ZCrGalXVHSLjY80WjaCFAGdZjrk/edit#slide=id.p

**Comment by Mashenka** [comment]
relevant designs 
Product landing pages in WordPress control panel - https://projects.invisionapp.com/d/main#/projects/2819220
WP-Property UI redesign concepts: https://projects.invisionapp.com/d/main#/projects/3845200
![image](https://cloud.githubusercontent.com/assets/5111163/14422249/71f67bc4-ffde-11e5-8dfb-97ec0f2ec394.png)

**Comment by Mashenka** [comment]
![1](https://cloud.githubusercontent.com/assets/5111163/14633778/cf28f3ea-0627-11e6-849d-746e6387944b.jpg)

**Comment by Mashenka** [comment]
![2](https://cloud.githubusercontent.com/assets/5111163/14633788/e033716a-0627-11e6-855d-81cb2358f47e.jpg)
![3](https://cloud.githubusercontent.com/assets/5111163/14633794/e60bc0ce-0627-11e6-9ccf-5fe4651fca3f.jpg)
![4](https://cloud.githubusercontent.com/assets/5111163/14633797/eca255c4-0627-11e6-8232-766d5fe699a4.jpg)
![5](https://cloud.githubusercontent.com/assets/5111163/14633808/f3e52096-0627-11e6-8a34-8d93186e3612.jpg)

**Comment by Mashenka** [comment]
This Set up Wizard should be shown only on new installs. But we need to think how it can be accessible for those who skipped those steps and want to do them in future.

So we need to create options:
- [x] for those who will **install wp-property first time,** there should be ability to go back to set up wizard if they leaved it accidentally or just skipped
- [x]  option which will revert wp-property configuration. There should be list of revisions. So each time someone is open set up wizard you need to save his current wp-property configuration and show revisions in Help tab.
  We have option to save and restore configuration at the moment in Help tab - http://screencast.com/t/BSlHvT78RB

Regarding second slider

The list of property types: They all should be marked as searchable and Location matters 
http://screencast.com/t/l1B66fMoeI
- House
- Condo
- Townhouse
- Multi-Family
- Land
- Commercial

If someone select 

**House, Condo,Townhouse,Multi-Family**,
following attributes should be created
- **Address**  Data Entry - Free Text Search Input - Free text 
  Attribute should be chosen  for automatic geolocation in Settings/Main tab
- **City**
- **Price** Data Entry - Currency Search Input - Range Dropdown
- **Bedrooms** Data Entry - Number
- **Bathrooms** Data Entry - Number
- **Total Rooms** Data Entry - Number
- **Living space**
- **Year Built**
- **Fees**
- **Features (taxonomy)**
- **Community features (taxonomy)**

**Commercial**
- **Address**  Data Entry - Free Text Search Input - Free text 
  Attribute should be chosen  for automatic geolocation in Settings/Main tab
- **City**
- **Price** Data Entry - Currency Search Input - Range Dropdown
- **Year Built**
- **Fees**
- **Features (term)**
- **Community features (term)**
- **Business purpose**

**Land**
- **Address**  Data Entry - Free Text Search Input - Free text 
  Attribute should be chosen  for automatic geolocation in Settings/Main tab
- **City**
- **Price** Data Entry - Currency Search Input - Range Dropdown
- **Year Built**
- **Fees**
- **Features (term)**
- **Community features (term)**
- **Lot size**

So that will be final list for Developer tab

**Comment by Mashenka** [comment]
Fatal error: Can't use function return value in write context in Z:\home\wizard.loc\www\wp-content\plugins\wp-property\static\splashes\install.php on line 41

when activating plugin on new install

**Comment by Mashenka** [comment]
* [ ] Styling issue. on all pages this white arrow
![image](https://cloud.githubusercontent.com/assets/5111163/19693860/d1aadaae-9ae5-11e6-86b1-d76e0972c144.png)

* [ ] next page is loading very slow

* [ ] last page do not link to single property or overview and just reloads

**Comment by Mashenka** [comment]
- [x] Styling issue. on all pages this white arrow
  ![image](https://cloud.githubusercontent.com/assets/5111163/19693860/d1aadaae-9ae5-11e6-86b1-d76e0972c144.png)
- [x] button in order manually save current configuration to database

![image](https://cloud.githubusercontent.com/assets/5111163/19695944/c024bb94-9aed-11e6-8fec-4aefa9d2033d.png)
- [x] next page is loading very slow. 
- [x] Let's save all settings on the last slider
- [x] last page do not link to single property or overview and just reloads
- [x] widgets are not showing when I select them
- [x] change words on first slide, instead of "congratulation, you have set up" put "Welcome to"
- [x] make some dummy properties featured
- [x] make the titles different for the last 5 properties
- [x] bedrooms, bathrooms, total rooms should be numeric data entry
- [x] term means that this is taxonomy and should be added to the terms tab if terms add-on exist or if not wp-property has 2 default taxonomies  - features and community features

So please remove that
![image](https://cloud.githubusercontent.com/assets/5111163/19694826/75474ffa-9ae9-11e6-80e9-82c7fd865186.png)

and also number of rooms delete. it is the same of total rooms
- [x] last slider shouldn't go to the first
- [x] option to create new page

![image](https://cloud.githubusercontent.com/assets/5111163/19695868/80e0dbb6-9aed-11e6-9c36-3b378161d905.png)

**Comment by Mashenka** [comment]
- [x] "List Property Page" need to change "Choose widget which you would like to see on Properties Page"
- [x] Can we speed up the process of saving data on last step? It is really very slow.

About last slider
- [x] Should be **Single property page**
- [x] the link Single property page takes me not to the property page(at least template wasn't property.php) 
- [x] it is creating dummy properties every time I go to the last step. That should be done only once
- [x] permalinks issue - https://github.com/wp-property/wp-property/issues/314
- [x] [property_overview] shortcode wasn't added to Properties page
- [x] Properties page is not opening from set up assistant. I have created new page but it still opens default one, which is property which is 404
- [x] links should open pages in new window
- [x] when I first time created new page for Properties page, it didn't allow me to check it on last step with error "Not enough data or something like this"

![image](https://cloud.githubusercontent.com/assets/5111163/19925765/0ff6bffc-a0fa-11e6-8757-9d4df43a46ac.png)

**Comment by Mashenka** [comment]
- [x] Google maps on single property pages not showing, because they require API keys. Need to think how to fix that. probably need to add separate step in order to put API keys for maps.
- [x] Address attribute should be automatically checked as for automatic geolocation
- [x] let's add child properties within dummy or do not show option to add that widget in wizard
- [x] types should be searchable and location matters - 
  ![image](https://cloud.githubusercontent.com/assets/5111163/20003029/a0df2c6e-a28c-11e6-88ba-be43d4686fca.png)
- [x] need to fix conflicts with latest branch

**Comment by Mashenka** [comment]
- [x] all attributes in single properties should be filled with some values, including features and community features
- [x] API key now is mandatory, not optional. Need to add note, like this.
  Google Maps requires API key to be shown on your single property pages.
  ![image](https://cloud.githubusercontent.com/assets/5111163/20105583/cd9dac0c-a5da-11e6-8ff1-8b5042447453.png)

Link [Where I can take it?](https://developers.google.com/maps/documentation/javascript/get-api-key)
- [x] no default attributes were added. 
  ![image](https://cloud.githubusercontent.com/assets/5111163/20105841/cc97fd7a-a5db-11e6-8fde-94d5e8fe8ee9.png)
- [x] where is question, which widgets to add to Properties page? There should be questions. 
  **Choose widget which you would like to see on Properties Page** and 3 widgets: Property Search, Featured Properties and Latest Properties

**Comment by Mashenka** [comment]
- [x] remove optional word for api key slider. Just explain why do they need it.
  _Google Maps requires API key to be shown on your single property pages. _
  and also words enter your  api key and than link where I can take it. 

These words are not true:
Note, Google maps has it's own limit of usage......bla bla bla , so do not include them at all
- [x] merge latest branch

**Comment by Mashenka** [comment]
- [x] Add new slider with option to chose layouts. This functionality already in latest branch. I working to add new layouts at the moment. Anton is working on layouts, so if you have questions you can ask him.
- [x] add new slider with freemius question. This is new option which also available in latest branch. freemius is integrated extension in order to use statistic from users site. when you activate wp-property you will see notice with question "Don't you mind we will use some stats from your site". I have sent you credentials to freemius. where you can find our projects an docs about intergation

At the moment freemius settings you can find here, if you think we need other place for that you can suggest
https://github.com/wp-property/wp-property/blob/latest/wp-property.php#L67

**Comment by ElenaRad** [comment]
Fixes: @raj-uimatic, please fix these. Layouts page will be done by Den, so do not do anything with that.  

- [x] 1.  Remove this screen. Make freemius essentially be that screen

- [x]  2. Make the whole blue box/line a button, so the user can click on that element. 

- [x]  3. Get rid of "Add widget to the single property pages?" option.

- [x]  4.  Make these 2 options automatic. 

- [x]  5.  This page should automatically go to "all Properties" page in the backend. 

- [x]  6.  Get rid of this page altogether. 

- [ ]  7. Let's make this slider with steps: Next and Previous, so the user can easily navigate. 


![image](https://cloud.githubusercontent.com/assets/19193013/20521500/388ba378-b0b4-11e6-97fb-d80146906c85.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20522436/f68d823e-b0b8-11e6-993b-322d2a3da834.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20522625/fde2ad2e-b0b9-11e6-9343-3d1109a116af.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20522660/30b36ee6-b0ba-11e6-91bd-af622a62cfa5.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20522709/6b6a0c0c-b0ba-11e6-95ec-738b54deeb35.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20522733/88988f38-b0ba-11e6-80d0-4c4b20bda0bc.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20522904/393e4d0a-b0bb-11e6-91e4-abe38c32ca51.png)

**Comment by ElenaRad** [comment]
@SoSeductive 

Add 2  pages with 3 layouts each. 

![image](https://cloud.githubusercontent.com/assets/19193013/20523388/7517d6f0-b0bd-11e6-897e-255829fcccaa.png)

**Comment by ElenaRad** [comment]
@raj-uimatic  When I click on any of the pages, I get this error:

![image](https://cloud.githubusercontent.com/assets/19193013/20527792/60f838ee-b0d2-11e6-8648-9931d6839616.png)

**Comment by ElenaRad** [comment]
@raj-uimatic 

I have agreed on the set-up wizard  for it to create some properties. however there are no properties when I go to "All Properties"    please look into this.

**Comment by ElenaRad** [comment]
@raj-uimatic  The idea here is to make this Box a part of the screen as it looks completely different from the rest of the slides.

* [x]  1. The whole box, can you make it so it looks like a part of the screen, instead of the box, so the bg for this element should have the same bg as the whole screen (let me know if you need elaboration on this) 

* [x]  2. Hide all these elements altogether ( W + FS) 

* [x] 3. Get rid of the grey bg and make it the same as the bg of the whole screen. 

* [x] 4. Hide these elements (Privacy Policy and Terms of Use) 

![image](https://cloud.githubusercontent.com/assets/19193013/20604751/af7992ac-b270-11e6-9369-c89424641fe6.png)

**Comment by ElenaRad** [comment]
* [x] Get rid of this text and instead have it say:  If you do not see your property type click here" . Make it clickable and be a drop down, so when the customer clicks on this element, it will expand and say this: 
" Custom Property Type can be created and managed in Properties/Settings/Developer Tab/Terms" And if possible have a button that says: Create custom property type here" which will redirect the client to the Developer Tab. 

![image](https://cloud.githubusercontent.com/assets/19193013/20604959/b875f37c-b271-11e6-9ec0-a0afbe30ce99.png)

**Comment by ElenaRad** [comment]
@raj-uimatic 

*[ ] Get rid of Facebook Tag: 

![image](https://cloud.githubusercontent.com/assets/19193013/20605299/4bf29e92-b273-11e6-9441-bcaf9ead9e92.png)

**Comment by ElenaRad** [comment]
@raj-uimatic 

* [x] Get rid of "Property Term Single ( everything that pertains to this option) 

* [x] Property Single will remain, but change the text to say: This is how your Single Property Page will look like. 

* [x] On Property Single, leave one layout "Single Property" 

* [x] Search Results: Rename to "Property Overview Page".

* [x] Search results:  Applies only when layout is selected   change this to " This is how your Property Overview Page will look like.

* [x] Get rid of the drop downs All of them, they are confusing. 

* [x]  Leave the layouts that are shown below and make sure they are all aligned and not all over the place and make sure that the layout squares are all the same sizes: 

![image](https://cloud.githubusercontent.com/assets/19193013/20605833/fa8ff858-b275-11e6-8526-777bec1bce55.png)


![image](https://cloud.githubusercontent.com/assets/19193013/20605463/3d366950-b274-11e6-8e01-a68d16dd5b66.png)

**Comment by ElenaRad** [comment]
@raj-uimatic 

We are going to combine 3rd, 4th and last pages.

* [x] 3rd page will be Layouts Page. 

* [x]  4th page we are going to get rid of and set default properties page as Default. 

* [x] Last Page: On the last page it should say: We have created test properties for you. Below we will have two buttons  "Great, take me to my properties" this button will be redirected to backend "All Properties"  and this button will be blue.  The Second button will be grey and it will say "Skip this step" and it will take them to their dashboard. 


![image](https://cloud.githubusercontent.com/assets/19193013/20606167/e170b004-b277-11e6-8eb6-e759c7150d13.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20606178/f1de9b54-b277-11e6-89d9-f2ab4efb0398.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20606210/1cce2abe-b278-11e6-9f7b-8e6508781a0d.png)

**Comment by ElenaRad** [comment]
@raj-uimatic  Could you please read the instructions for the last page of the wizard? It should not look like it is.

**Comment by raj-uimatic** [comment]
@ElenaRad I am updating the labels.

**Comment by andypotanin** [comment]
Closing, implemented.
