### ISSUE TITLE
Need to add some toggle option/marker in backend All properties page for Overview

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#240]
Or disable ability to toggle at all as there's no benefit to it.

![image](https://cloud.githubusercontent.com/assets/5111163/13501637/24878630-e170-11e5-9a9a-729241d942e3.png)

**Comment by ewsopp** [comment]
Why do we even have the ability to expand/collapse this area? It serves no purpose...

**Comment by Mashenka** [comment]
yes, I agree @ewsopp  this confuse  a lot of our users

**Comment by ewsopp** [comment]
We should just remove the ability to collapse the block altogether. Lets keep it simple...
