### ISSUE TITLE
There is no ability to delete lats item in Attributes,Property type and Meta tab

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#241]
Within WP-Property you can find them in Properties/Settings/Developer tab.
There exist logic that there should be at least one item in the list, so there is no ability to delete last one

User notices from wordpress - https://wordpress.org/support/topic/cant-properly-remove-community-features-terms?replies=4#post-8070870

**Comment by ewsopp** [comment]
When I try to delete the last meta attribute, it adds four attributes back.

![image](https://cloud.githubusercontent.com/assets/5578537/13785040/11485964-eaa8-11e5-9ede-d5e02441a6a0.png)

**Comment by ewsopp** [comment]
I should be able to delete all meta attributes.
