### ISSUE TITLE
UNC Path Normalization Errors

### ISSUE THREAD

**Issue by seanvfs** [wp-property/wp-property#243]
Function wp_normalize_path() usage causes include/require failure on UNC paths.
This causes fatal errors which disable the site.

/vendor/plugins/wp-meta-box-utilities/wp-meta-box-utilities.php Line 77
/vendor/libraries/usabilitydynamics/lib-ud-api-client/lib/classes/class-admin.php Line 99

I would suggest doing a check for a drive letter at the beginning of the path or another method to test for UNC and alter logic accordingly to prevent this problem.

**Comment by pemaxim** [comment]
The `wp_normalize_path()` is native WordPress function.
More details you can find here: https://developer.wordpress.org/reference/functions/wp_normalize_path/

I guess, you are using Windows OS since Unix systems do not have drive letter. 
What exactly does the function break in your UNC path?

**Comment by seanvfs** [comment]
If the WP Property plugin is used in a hosting scenario where UNC storage is involved, the plugin as a whole does not work.  The way that includes and requires are handled with path manipulation causes incorrect paths to be used, therefore the plugin ceases to function.

Thank you,

 Sean Herbert

Director of Technology

VisionFriendly.com

sean@visionfriendly.com

630-553-0000 x105

**Comment by SoSeductive** [comment]
We use native WordPress function, so I think this issue not in our plugin.
