### ISSUE TITLE
Add date picker to Search Input option

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#248]
We have [settings](https://www.usabilitydynamics.com/product/wp-property#documentation=wp-property-help/wp-property-settings-developer-tab) for Data Entry and Search Input of the attributes

At the moment we have date picker in data entry  but not in search input

**Comment by mehulkaklotar** [comment]
Search Input option has static fields inserted right now unlike Data Entry field which has dynamic fields inserted via `ud_get_wp_property` function. So would you like to have fields from the same function itself?

Search Input option has some different fields though!

**Comment by Mashenka** [comment]
I have talked to the developer. your question is not clear and he need to spend time in order to answer. You can do this task doing your best and we will check the results.

**Comment by mehulkaklotar** [comment]
If we add date picker to Search Input Fields, what will it be used for in search form `[property_search]`?
Is it going to be range of date to search for properties?

**Comment by Mashenka** [comment]
Yes, range of date. 
you can use our widget Property Search or shortcode [property_seacrh]. Parameters for shortcode you can find here - https://www.usabilitydynamics.com/product/wp-property#documentation=wp-property-help/wp-property-shortcode-cheat-sheet

**Comment by Mashenka** [comment]
regarding backend attribute can be in search box only if the Data Entry and Search Input will be set up correctly https://www.usabilitydynamics.com/product/wp-property#documentation=wp-property-help/wp-property-settings-developer-tab
![image](https://cloud.githubusercontent.com/assets/5111163/14420578/8ee8768c-ffd5-11e5-9b93-ef8932d57b66.png)
