### ISSUE TITLE
[Feature Request] Option to choose Infinite Scroll instead of Ajax Pagination

### ISSUE THREAD

**Issue by raphaelsuzuki** [wp-property/wp-property#25]
Would be very handy if we could choose to use some sort of Infinte Scroll (append items to the bottom of the page) instead of the current numbered Ajax Pagination.

**Comment by raphaelsuzuki** [comment]
Would also be nice to have some more options, like traditional numbered pagination, instead of the slider.

**Comment by pemaxim** [comment]
Yes, thank you for the idea. We're thinking about some refactoring of [property_overview] shortcode and adding different types of pagination including traditional numbered one. Probably, we will implement it in near future.

**Comment by raphaelsuzuki** [comment]
I'm getting this error whenever I click on a next button (FancyBox is removed):

`TypeError: jQuery(...).fancybox is not a function`

Maybe FancyBox isn't called with a conditional.

**Comment by raphaelsuzuki** [comment]
You have implemented some of these features into your new theme, Madison, including infinite scroll. Any chance of seeing them available in the plugin?

**Comment by andypotanin** [comment]
I'm not sure if infinite scrolling (specifically the front-end JavaScript code) should be handled by the plugin, as it is more of a UX feature, seems to fall under the realm of themes - but I could be wrong. I'll add this to our task queue for review.

**Comment by raphaelsuzuki** [comment]
Since WPP handles pagination, it would be natural that it also supports infinite scroll, that's already built in for those who have Jetpack installed.

**Comment by Mashenka** [comment]
A new type of pagination "Load more" was added in 2.3.0
