### ISSUE TITLE
title alt and caption option of the images

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#256]
4 images in the sample that reflect in the "view source"

1st image does not have the title, alt or caption completed - result below

2nd has the Title and Alt Completed as “Image Title Tag 2 and “ALT tag 2” - result below

3rd has the Title and ALT completed plus a Caption as “Image Title Tag 3” and “ALT tag 3” and “Caption for 3rd Image” - result below

4th has just an ALT tag inserted as “Just the ALT Tag” but you’ll see in the source code simply “” meaning the ALT tag doesn’t function at all – except to duplicate content that might be in the caption or title tag. - result below

They produced the following:
1st Image title=" - A Sample Property with 3 images"
alt=""
class="wpp_gallery_widget_image size-thumbnail "
width="195"
height="130"/>

2nd Image title="Image Title Tag 2 - A Sample Property with 3 images"
alt="Image Title Tag 2"
class="wpp_gallery_widget_image size-thumbnail "

3rd Image: title="Caption for 3rd Image"
alt="Caption for 3rd Image"
class="wpp_gallery_widget_image size-thumbnail "
4th Image
title=" - A Sample Property with 3 images"
alt=""
class="wpp_gallery_widget_image size-thumbnail "

4th has just an ALT tag inserted as “Just the ALT Tag”  but you’ll see in the source code simply “” meaning the ALT tag doesn’t function at all – except to duplicate content that might be in the caption or title tag.

Hierarchical Order / Priority appears to be CAPTION then Title with no information input for ALT

reference to wordpress topic - https://wordpress.org/support/topic/if-empty-then-auto-insert-image-title-and-alt-tag?replies=7#post-8284202

**Comment by mehulkaklotar** [comment]
6125a57 resolves the issue
