### ISSUE TITLE
WordPress 4.5 File Upload data input has issue

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#257]
it looks like that on backend when uplaod images

![image](https://cloud.githubusercontent.com/assets/5111163/14707670/8350353e-07ce-11e6-9f84-a1312ffdf385.png)

but do not have any issues on frontend

**Comment by alimuzzaman** [comment]
Conflict with new version of underscore with vendor/plugins/wp-meta-box.
Is it possible to update wp-meta-box(If they already fixed this)?
http://stackoverflow.com/questions/30608576/pass-object-to-underscore-js-template

**Comment by alimuzzaman** [comment]
can be solve by overriding  image-advance.php and image-advance.js

**Comment by pemaxim** [comment]
@alimuzzaman 

> Is it possible to update wp-meta-box

Yes, it's possible. Need merge their repository with our one.

> (If they already fixed this)

Did they? Did you check?

> can be solve by overriding image-advance.php and image-advance.js

Be sure that all changes you are doing in meta-box plugin will not disappear on merging our meta-box with native meta-box plugin.

**Comment by Mashenka** [comment]
@alimuzzaman issue still exist - https://workspace.uds.io/wp-admin/post.php?post=576401&action=edit

why it is in review?
