### ISSUE TITLE
Update meta box library 

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#258]

**Comment by alimuzzaman** [comment]
revert this [commit ](https://github.com/wp-property/wp-property/commit/2830efa210b0bb08ab7da35077736047c173dde2) when done.
https://github.com/wp-property/wp-property/commit/2830efa210b0bb08ab7da35077736047c173dde2

**Comment by SoSeductive** [comment]
@alimuzzaman I am working now with this issue and dont understand how i can update meta box library. Can you help me?

**Comment by alimuzzaman** [comment]
@SoSeductive  Metabox is located in `wp-property\lib\features\meta-box\meta-box`.
And loaded in https://github.com/wp-property/wp-property/blob/latest/lib/classes/class-meta-box.php#L60

**Comment by SoSeductive** [comment]
@alimuzzaman Yes, I know this. But I asked - how I can update it? Where i can get new version? I can't found it on `MetaBox` site. Maybe this libs on another place, maybe you know?

**Comment by alimuzzaman** [comment]
@SoSeductive it's directly from [wordpress.org](https://wordpress.org/plugins/meta-box/)

**Comment by Smoot328** [comment]
@ewsopp Please provide @SoSeductive the license so he can complete this issue.

**Comment by SoSeductive** [comment]
@Smoot328 @ewsopp Dmitry already gave me access to metabox admin page. I have already updated addons on workspace. We are testing it now

**Comment by Mashenka** [comment]
@alimuzzaman metabox plugin with it's add-ons updated (for now only on workspace). should we revert [your commit](https://github.com/wp-property/wp-property/commit/2830efa210b0bb08ab7da35077736047c173dde2)?

**Comment by alimuzzaman** [comment]
@Mashenka @SoSeductive I had already reverted that commit.
Nothing need to revert.
Although I had edited metabox directly, for #257 in this commit 358a7589b495053f417231daa33cf8e509ac64a9. To be sure please review that issue again.
Hopping that issue has been solved the new meta box.

**Comment by SoSeductive** [comment]
@Mashenka Done
