### ISSUE TITLE
Add option: Select default value on list

### ISSUE THREAD

**Issue by dchacons** [wp-property/wp-property#268]
It will be great to have the chance for select the default value of a list field.

For example, if the list have this options: available, already sold, already rented, retired, it will be great to display a default value that exist in the list, for example available.

**Comment by Mashenka** [comment]
Hello.

We have [special place for wp-property's ideas](http://feedback.usabilitydynamics.com/forums/95259-wp-property) where users can create ideas and vote if there exist ones.
I have found similar ideas, so you can vote for them, we are trying to implement the most popular
http://feedback.usabilitydynamics.com/forums/95259-wp-property/suggestions/10686735-default-value
http://feedback.usabilitydynamics.com/forums/95259-wp-property/suggestions/12462213-default-values-in-lists-for-searhing-a-property

I will close this issue on github, cause we are not storing ideas here.

Regards.
