### ISSUE TITLE
trashed properties do not have pagination on all properties page

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#272]
happen only when you have 0 published properties
![image](https://cloud.githubusercontent.com/assets/5111163/15862413/457fc8ee-2cd8-11e6-8d91-8cd03e1d1967.png)

**Comment by alimuzzaman** [comment]
Can't replicate.

**Comment by Mashenka** [comment]
I can show you. Call me

steps to replicate:

1) You need to have more than 20 properties in trash status
2) You need to have 0 published, draft or properties with other statuses 
3) View trash properties , and you will see that there is not pagination

![image](https://cloud.githubusercontent.com/assets/5111163/16001468/cb0f530e-315a-11e6-92ec-2dbd6edf4400.png)

![image](https://cloud.githubusercontent.com/assets/5111163/16001533/37ca553e-315b-11e6-84b1-7d8d19d5726e.png)
