### ISSUE TITLE
Add Property ID to the list of default attributes if someone need to find it.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#273]
On property overview shortcode we have parameter property_id or ID 
![image](https://cloud.githubusercontent.com/assets/5111163/15961085/86d9bb58-2f0b-11e6-8700-de9229a9ece3.png)

But some users is stuck how to find it.

Let's add it as not editable attribute on Edit Property page and also as not removable on Developer tab, where user can set up Only Search Input (Data Entry is also should be uneditable)

Example of look

![image](https://cloud.githubusercontent.com/assets/5111163/17015853/ff5788b4-4f34-11e6-80fa-b6408614f184.png)

https://www.usabilitydynamics.com/product/wp-property#documentation=wp-property-help/wp-property-shortcode-cheat-sheet

https://www.usabilitydynamics.com/product/wp-property#documentation

**Comment by raj-uimatic** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/5083106/17056684/a39ca01e-5032-11e6-913f-11ba75812156.png)

**Comment by Mashenka** [comment]
We have option to set up backend filter on All properties page, can't find what should I set to see ID attribute there

![image](https://cloud.githubusercontent.com/assets/5111163/17097391/4176b2d6-5266-11e6-95ed-1a6c944797e4.png)

https://www.usabilitydynamics.com/product/wp-property#documentation=wp-property-help/wp-property-settings-developer-tab

Will there ability to search by ID ?

**Comment by Mashenka** [comment]
@andypotanin  Question from Raj: Right now I am not setting any hidden/default value. The "data entry" gets discarded for the ID field. Should there be any default value associated with it ?

**Comment by andypotanin** [comment]
@raj-uimatic I think you're talking about the issue with checkboxes not having a default value? If so, we usually insert an element hidden element with same name before the checkbox. That way when no option is made the value of the hidden field prevails, e.g.:

```
<input type="hidden" name="some_field" value="false" />
<input type="checkbox" name="some_field" value="true" <?php if( is_selected() ) ... ?> />
```

Or I don't understand the question.

**Comment by Mashenka** [comment]
@andypotanin Raj meant that data entry is hidden and there should be something by default for property id


just some notes:

as post_id is meta WordPress attribute it should be updated on all properties before it start showing on edit property page or you will have ability to search by ID

didn't find solution to work around this

**Comment by SoSeductive** [comment]
@Mashenka Done 
![2683bb0fcb](https://user-images.githubusercontent.com/2156026/41726893-c579f252-757b-11e8-8fac-01c6861c51aa.png)
![4e9fae7103](https://user-images.githubusercontent.com/2156026/41726895-c5a923f6-757b-11e8-97b0-290484a00711.png)
