### ISSUE TITLE
Missing template files

### ISSUE THREAD

**Issue by tgoeminne** [wp-property/wp-property#274]
When installing this plugin, you get 500 error in admin side after activating, when checking the error logs, it seems to throw errors because missing template files, wp-meta-box

You should at least provide the template files or list which other plugins you must install before installing this plugin. Otherwise every new user will get 500 errors on their admin.

**Comment by Mashenka** [comment]
Hello.

Did you try to delete, upload plugin from WordPress and try install it again. Probably you delete something accidentally in wp-property. You can also use our support for such questions here - https://usabilitydynamics.com/contact-us/

Or can you send particular error which you had.

Also try to deactivate all third party plugins on your site to investigate the issue and check if you have the latest versions of them
