### ISSUE TITLE
Standard attributes

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#281]
In Settings Developer tab we want to create Standard attributes. Those attributes will be used in our other services such as PDF,Importer and our custom themes. So for just wp-property users at the moment there won't be particular benefit of this new option.

Difference between default attributes and Standard attributes:
Default/Custom attributes are just attributes which exist in Developer tab on first install of the plugin or users creating them by themselves. (We already have such option)

Standard attributes should be matched with Default ones or newly created by users. So for one default or new attribute can be selected one of standard one.

This cab be done as validation so when the you match your attribute with standard there can't be green check mark. Standard attributes also will have icons to select, which will be used on mentioned products.

![image](https://cloud.githubusercontent.com/assets/5111163/17144673/3aa901fc-5360-11e6-8d4c-a7e9b699dff6.png)

Predefined list of attributes which we will need for PDF:
1. Price
2. Address
3. Bedrooms
4. Bathrooms
5. Living Space size Sq ft.
6. Features (term)
7. Community features (term)

Predefined list for Importer:
all from above and
8. Total Rooms
9. Year Built
19. № of flors
11. Lot size, acres
12. Neighborhood (term) 
13. Fees
14. Status

**Comment by Mashenka** [comment]
Merge conflict
![image](https://cloud.githubusercontent.com/assets/5111163/17773166/acf6558c-6555-11e6-967e-19bfc31e77b4.png)

**Comment by Mashenka** [comment]
Also need:
- [x] add information with question mark and pop up. 

Information for pop-up window

This option designed to help us find which attribute you want to show as Price, Address, etc and place it in correct place in our templates.
- [ ] hide this option for those who do not have those services. Just create separate option In settings/Main tab in Advanced options section in order to enable it. By default it should be disabled.
  ![image](https://cloud.githubusercontent.com/assets/5111163/17780874/a90123ec-6575-11e6-8858-7686b4a619af.png)

**Comment by Mashenka** [comment]
Icons for current list of standard attributes
1. price - https://thenounproject.com/search/?q=price&i=16768
2. address - https://thenounproject.com/search/?q=address&i=547738
3. bedrooms - https://thenounproject.com/search/?q=bedroom&i=25715
4. bathrooms - https://thenounproject.com/search/?q=bathroom&i=535184
5. Living Space - https://thenounproject.com/search/?q=size&i=338490
6.  Features  - https://thenounproject.com/search/?q=features+list&i=59948
7. community features - https://thenounproject.com/search/?q=features+list&i=294090
8. total rooms  - https://thenounproject.com/search/?q=rooms&i=189840
9. year of built - https://thenounproject.com/search/?q=year+of+built&i=573397
10. number of floors - https://thenounproject.com/dremchee/collection/houses/?oq=floors&cidx=3&i=590421
11. Lot size - https://thenounproject.com/term/plot/532585/
12. Neighborhood  - https://thenounproject.com/search/?q=Neighborhood+&i=15064
13. fees - https://thenounproject.com/term/coins/42001/
14. status - https://thenounproject.com/cfpb_minicons/collection/status-icons/?oq=status%20symbol&cidx=1&i=89616

**Comment by Mashenka** [comment]
Fatal error: Can't use function return value in write context in Z:\home\wpp-org.loc\www\wp-content\plugins\wp-property\lib\classes\class-settings.php on line 137

**Comment by Mashenka** [comment]
![image](https://cloud.githubusercontent.com/assets/5111163/18050254/29508992-6df6-11e6-80ae-01d1b767df3a.png)

Can you use attribute title in  order to show that information?

**Information text:**
This option designed to help us find which attribute you want to show as Price, Address, etc and place it in correct place in our templates.

**Comment by andypotanin** [comment]
@Mashenka why should "Enable Standard Attributes..." be a question mark? Do we use that form in any of the other options?

**Comment by Mashenka** [comment]
@andy just because I like that more than pop up, that's all. Do you have other ideas? I don't mind.

Previously Raj did like that, but I didn't like
![image](https://cloud.githubusercontent.com/assets/5111163/18052117/2f8a5d96-6e01-11e6-9380-95a80fc5e2ce.png)

**Comment by andypotanin** [comment]
@Mashenka @raj-uimatic I think a popup is okay but isn't there a native WordPress style we can use?

**Comment by Mashenka** [comment]
@andypotanin I have asked to use attribute title. Not sure if he used it. At the moment it looks like this
![image](https://cloud.githubusercontent.com/assets/5111163/18054231/ac234d18-6e0b-11e6-8277-3005629823c2.png)

**Comment by raj-uimatic** [comment]
@andypotanin  plugin is having jquery-ui library included. So right now "title" tags are inheriting the styles from it. So technically it is not the default "title" attribute's styling being used.
Are we looking for something else ?

**Comment by andypotanin** [comment]
@raj-uimatic well in general we want to use native WP styles when possible, unless not available. Are you telling me there are no no native styles for a tooltip?

**Comment by raj-uimatic** [comment]
@andypotanin  No other default alternative to "title".
But we do have "wp-pointer" if that fits the situation.
Reference image attached 
![screenshot_4](https://cloud.githubusercontent.com/assets/5083106/18054650/546c93c4-6e22-11e6-8057-fad80438b800.png)

**Comment by andypotanin** [comment]
@raj-uimatic I believe wp-pointer looks better, can we have the pointer be triggered on click/hover? I see there's a "dismiss" option there, doesn't really apply to our case unless have the "helper pointers" show up automatically which is good in some cases but not in this one.

**Comment by raj-uimatic** [comment]
Yes we can fire this on hover. But yes automatically firing will not be good UX.
In our case we want this to appear each time on hover ?

**Comment by andypotanin** [comment]
@raj-uimatic I'm not sure when it should appear because I haven't used this UI yet, I just want to make sure we don't add new styles if we don't have to. Up to you and @Mashenka when it appears (click/hover).

**Comment by andypotanin** [comment]
@Mashenka is this not done yet?

**Comment by Mashenka** [comment]
@andypotanin for wp-property yes. 
You can check that in special branch
Need to add for terms also
