### ISSUE TITLE
Need to change links in screen option sidebars

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#283]
![image](https://cloud.githubusercontent.com/assets/5111163/17249879/a2248940-55aa-11e6-8f46-d02d39617346.png)

https://www.usabilitydynamics.com/product/wp-property/
https://wordpress.org/support/plugin/wp-property/
https://www.usabilitydynamics.com/product/wp-property/docs/home

**Comment by SoSeductive** [comment]
@Mashenka Done
