### ISSUE TITLE
Add new fields for Google Maps

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#285]
browser key for displaying google map on frontend
server key for revalidating addresses

at the moment we have one key for both things in Settings/Main tab, but this is not correct
![image](https://cloud.githubusercontent.com/assets/5111163/17475869/d408e902-5d65-11e6-96b4-fbba2cf6700a.png)

at the moment those options not optional but mandatory

**Comment by alimuzzaman** [comment]
@Mashenka Helps are in help wp context help menu at top. Please review.

**Comment by Mashenka** [comment]
checking

**Comment by Mashenka** [comment]
Great. Closing

**Comment by antonkorotkov** [comment]
@alimuzzaman Just wanted to clarify if Supermap and Revalidate address function consider these settings. Can you confirm?

**Comment by alimuzzaman** [comment]
On browser it's use browser key.
On server side side it's use server key. if not exist it's use browser key.
