### ISSUE TITLE
WPML. 404 page on single property page in other language

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#291]
Here is property in Russian, it shows 404 - https://workspace.uds.io/ru/properties-2/mls-id-c3481405-city-toronto-price-179000-00/

This is the same in English  - https://workspace.uds.io/properties-2/mls-id-c3481405-city-toronto-price-179000-00/

Previously we didn't have such issue with WPML plugin.

Posts do not have such issue. So it should be something with wp-property
https://workspace.uds.io/ru/%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82-%D0%BC%D0%B8%D1%80/

**Comment by alimuzzaman** [comment]
The problem is only with same slug.

**Comment by Mashenka** [comment]
do you mean with permalink? can you explain?

**Comment by alimuzzaman** [comment]
yes

**Comment by Mashenka** [comment]
Why there is no any info, map on single property page - 
https://workspace.uds.io/properties-2/mls-id-c3481405-city-toronto-price-179000-00/

**Comment by alimuzzaman** [comment]
What do you mean by no any info, map?

**Comment by Mashenka** [comment]
attributes, map
just title was shown
in both english and other language
template is correct - default - property.php

https://workspace.uds.io/properties-2/mls-id-c3481405-city-toronto-price-179000-00/
https://workspace.uds.io/ru/properties-2/mls-id-c3481405-city-toronto-price-179000-00/

**Comment by Mashenka** [comment]
On single property page

Warning: Invalid argument supplied for foreach() in Z:\home\wpp-org.loc\www\wp-content\plugins\wp-property\lib\classes\class-wpml.php on line 39

Notice: Undefined index: property_groups in Z:\home\wpp-org.loc\www\wp-content\plugins\wp-property\lib\classes\class-wpml.php on line 374

Warning: array_keys() expects parameter 1 to be array, null given in Z:\home\wpp-org.loc\www\wp-content\plugins\wp-property\lib\classes\class-wpml.php on line 374

Warning: array_search() expects parameter 2 to be array, null given in Z:\home\wpp-org.loc\www\wp-content\plugins\wp-property\lib\classes\class-wpml.php on line 375

PHP vesrion `5.3.*.*`
Fatal error: Can't use function return value in write context in Z:\home\wpp-org.loc\www\wp-content\themes\wp-avalon\template-parts\content\content-property.php on line 82

**Comment by alimuzzaman** [comment]
I have removed first two commit because those are unnecessary after updates. New commit is for fix warning.

**Comment by Mashenka** [comment]
Now English version is showing 404
https://workspace.uds.io/properties-2/3351-cal-ave-salton-seacalifornia/
https://workspace.uds.io/ru/properties-2/3351-cal-ave-salton-seacalifornia/

**Comment by Mashenka** [comment]
error from workspace logs

`[12-Sep-2016 10:45:51 UTC] WordPress database error Table 'workspace.uds.io.wp_icl_string_urls' doesn't exist for query SELECT id FROM wp_icl_string_urls WHERE language='en' and url='/wp-admin/edit.php/?page=page_feps' made by WPML_ST_Page_Translations_Persist::fetch_or_create_url_id`

**Comment by alimuzzaman** [comment]
Can't replicate on local.

**Comment by Mashenka** [comment]
ok. can't also replicate at the moment
but there other thing
broken links of images on translated property
https://workspace.uds.io/ru/property/55-255-beach-walk/

this is error logs from workspace, you can save this link somewhere, it helps in troubleshooting - https://workspace.uds.io/logs.errvcicjbuysodil.php

**Comment by alimuzzaman** [comment]
_is_remote meta generate button added in settings help tab after clear cache button.
Automatically add _is_remote meta when duplicate media.

**Comment by alimuzzaman** [comment]
Button in help tab is added to fix previous image issue where future translation image will have _is_remote meta automatically.

**Comment by Mashenka** [comment]
This option should be invisible for those who do not have WPML plugins

**Comment by Mashenka** [comment]
Also is there ability to do that automatically when property is duplicating? Can you find some hook for that?

If not, the text of this option should be changed. 

_Generate images for duplicates of properties (WPML plugin option)_  [Generate]

**Comment by alimuzzaman** [comment]
Yes I already did that. Automatically will be done on image duplicate. It was the easy part. Please check it. Please check the text in the help tab I added.
`Generate _is_remote meta for all WPML duplicate images.  **Generate _is_remote meta**`

`If you have remote image as attachment then _is_remote meta is needed to be set true. But WPML doesn't copy all meta. So you should generate this meta by clicking this button if you got broken image.`

**Comment by Mashenka** [comment]
I have checked the text already and commented in previous comment, it should be changed
![image](https://cloud.githubusercontent.com/assets/5111163/18983933/64da980c-86f8-11e6-8b0e-5d36e810902f.png)
