### ISSUE TITLE
All Properties items tab not translatable

### ISSUE THREAD

**Issue by raphaelsuzuki** [wp-property/wp-property#3]
Some items in All Properties tab doesn't seem to have textdomain and aren't translatable:
- Pagination;
- Featured in sidebar: "Yes" and "No"
- Status: "Publish" and "Trash";
- Filter Results;
- "Display X Records" dropdown.

**Comment by pemaxim** [comment]
Thank you for pointing. Fixes will be added to WP-Property 1.38 version release.
