### ISSUE TITLE
WPML. Wrong count of properties

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#303]
For each language there should be own count
![image](https://cloud.githubusercontent.com/assets/5111163/19351115/19fc9e82-9163-11e6-8e4c-d7c3a9b2c0c7.png)

**Comment by alimuzzaman** [comment]
What do you mean by wrong count?
Do you want another filter for language on **Properties Search**?
Or new **Status** filter?

**Comment by ElenaRad** [comment]
We want the count for each language, so in the dropdown it should say: English: 2  spanish 30 english 20. 
We do not want them bundled like that, we want the user to pick properties according to the language.

**Comment by Mashenka** [comment]
![image](https://cloud.githubusercontent.com/assets/5111163/20933454/bdbec944-bbe0-11e6-9902-c27d9c6a3a0b.png)

I seems Elena misunderstood the issue.

@alimuzzaman 
There should be just correct count. If you are looking on English properties, so published properties should be also the same amount.

No need for languages in Status filter.

**Comment by Mashenka** [comment]
![image](https://cloud.githubusercontent.com/assets/5111163/20933731/a1767a60-bbe1-11e6-9976-2b33996c721d.png)

It seems Elena misunderstood the issue

@alimuzzaman There should be just correct number for published properties when you are looking on e.g English properties

No need for Languages in Status Filter

**Comment by alimuzzaman** [comment]
@Mashenka Make me clear. There is nothing wrong.
Published (281) is counting published property in all language.
Should that be only from selected language?
Published: 279 - 1 (Draft in english) + 1 +2 = 281
Total: 279 + 1 +2 = 282

**Comment by Mashenka** [comment]
ok. Leave like you did, Just make hierarchically like this

Published(280)
    -English (277)
    -Spanish (1)
    -Russian (2)

Draft(1)
     -English(1)

 Trashed(2)
     -English(1)
     -Russian(1)
