### ISSUE TITLE
Add-on:  Saved Search

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#312]
## **Feature Options**

---
1. Alerts for New Properties matching saved search criteria.
2. Alerts for changes to attributes on properties within saved search criteria (example: price change, date available change, etc).
3. Multiple saved searches per user.
4. Saved searches dashboard for user with ability to name and edit search criteria.
5. Signup confirmation with email validation.
6. Unsubscribe option.
7. Email template.
8. Email Frequency options. Instantly, Daily, Weekly
9. Maximum Listings per Email.
10. Stats option. What is the most searchable property type or some other attribute
11. Save search without an account. Prompt for email address when ‘Save Search’ button clicked.
12. Save search with an account.
13. Save search from within Super Map.
14. Save search from search results page.
15. Saved search landing page with unique urls and automated description content.

**Comment by andypotanin** [comment]
@ElenaRad we should keep this on UserVoice.

**Comment by Mashenka** [comment]
@andypotanin  Actually this is from our Google doc

**Comment by ElenaRad** [comment]
I think you were the one who told me to post it here :) @andypotanin
