### ISSUE TITLE
Property Attributes widget enhasment

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#313]
* [x] not showing show Detailed list  - display option, if sorted by groups enabled. [When you chose this option + chose group attributes.  Attributes won't be shown on single property page on front end at all]
* [x] Add default property's taxonomy to the list 
![image](https://cloud.githubusercontent.com/assets/5111163/19937064/742ab0d6-a128-11e6-85e4-46c2337fa8bf.png)

They are:
1. features
2. community features
3. property type
4. status

Also add to the list all terms if the wp-property-terms installed.

* [x] add new option/parameter to widget
make_terms_links=true/false

This option already exist in general, just do not exist in this widget

* [x] rename this widget to Property Details.

**Comment by alimuzzaman** [comment]
1. Is default property's taxonomy should add regardless of whether "Public & searchable" checked?
2. Slug of the default property's taxonomy.
3. Only widget title renamed.

**Comment by Mashenka** [comment]
1. No, only when "Public & searchable" checked
2. Slugs are property_type property_status property_location
   You can make other slugs for them in order not to have conflicts, like
   wpp_type wpp_status wpp_location
3. ok

**Comment by Mashenka** [comment]
- [ ] using this widget terms are not displaying. I have added widget here - https://workspace.uds.io/wp-admin/post.php?post=746947&action=edit

Just FYI: Don't pay attention on styles.

**Comment by alimuzzaman** [comment]
Maybe problem with sidebar. Work fine on local.

**Comment by Mashenka** [comment]
I have tested on different sites. Terms are not showing when I used that widget
