### ISSUE TITLE
Permalinks issue on Default property page

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#314]
Without setting "permalinks - post name" at the moment there is no ability to use Default Properties Page

![image](https://cloud.githubusercontent.com/assets/5111163/19966224/89c88e4e-a1d3-11e6-992b-f0f7fa9dd15c.png)

**Comment by andypotanin** [comment]
The "Default Properties Page" selection should still work, and on the front-end things should work WITHOUT permalinks enabled by requiring that a page be selected. We used to allow dynamic "property" page to be used, but now a page must be selected during setup, or we will create one automatically called "Properties".

This means that on new installs without permalinks the default property page will be available at something like `https://site.com/?page_id=14` if the ID of the new "Properties" page is `14`.

Also, convert the old-school dropdown into same element used by WooCommerce, not sure if its select2 or something similar:
![image](https://cloud.githubusercontent.com/assets/1255935/19967445/f2f715ac-a1d8-11e6-895e-98384f975510.png)

**Comment by andypotanin** [comment]
In fact, create a new page called "Properties" automatically during setup, as WC does. Then people should be able to change it later, using the dropdown.
