### ISSUE TITLE
Address attribute/Location Taxonomy

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#317]
Andy added new default taxonomy Property Location (`wpp_location`). It automatically takes terms from Address attribute
![image](https://cloud.githubusercontent.com/assets/5111163/20139683/f19330a4-a68f-11e6-8c1a-d1f69d21269c.png)
This Taxonomy is displaying only in backend in order not to duplicate same info on frontend.

So at the moment terms location pages are working very well. 
It looks like that now - site.com/taxanomy/term - and this page is displaying all properties with that particular term. Very cool if you need to see all properties from particular city or street.

And also there is hierarchical search by locations now.
![image](https://cloud.githubusercontent.com/assets/5111163/20141000/fdf85aca-a696-11e6-92c2-b5a1926b5cd7.png)

Issues:
* [ ] Property Location terms should be hidden on edit/add property page. 
* [ ] At the moment it is showing in both place on edit single property page in Meta Box and within attributes. Even when show native meta box disabled. Need to be only within attributes

Enhancement: 
* [ ] on frontend we need to display address attribute as clickable links for each term
![image](https://cloud.githubusercontent.com/assets/5111163/20141025/27c4b8bc-a697-11e6-8999-b942a9a34288.png)

**Comment by Mashenka** [comment]
- wpp_location should be hidden at all on edit/add property page. We need to show address attribute as clickable terms. Let me know if that possible

**Comment by alimuzzaman** [comment]
rewrite slug will be "location"?

**Comment by Mashenka** [comment]
wpp_location

**Comment by Mashenka** [comment]
yes

**Comment by Mashenka** [comment]
@ElenaRad why did you close this issue?

@alimuzzaman wpp_location should be hidden at all on edit/add property page. We need to show address attribute as clickable terms like: [Street](www) [City](www) [Country](www). Let me know if that possible

**Comment by ElenaRad** [comment]
@Mashenka  Because I thought it was done, we got rid of the meta box,  location is hidden and addresses are clickable: 

![image](https://cloud.githubusercontent.com/assets/19193013/20893676/4d793a4a-bb1b-11e6-9a61-381fdac605d3.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20893696/5db7d916-bb1b-11e6-8a49-2bedbf19d8b0.png)

**Comment by Mashenka** [comment]
see now
