### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error

### ISSUE THREAD

**Issue by ChrisBoothDigital** [wp-property/wp-property#328]
Receiving the following error when I attempt to activate the plugin on wordpress 4.6.1.

Parse error: syntax error, unexpected T_STRING in /home/content/74/8495874/html/rentalsBuild/wp-content/plugins/wp-property/wp-property.php on line 54

Anyone come across the same issue?

**Comment by andypotanin** [comment]
@ChrisBoothDigital I guess we're good here?
