### ISSUE TITLE
Layouts availability 

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#334]
All layouts should be enabled by default. So, the below image is displaying what the default settings have to be. The checkbox "enable layouts" should be checked by default.

![image](https://cloud.githubusercontent.com/assets/19193013/20436061/498b227a-adb7-11e6-9ced-073e8d4c85fe.png)

**Comment by SoSeductive** [comment]
@ElenaRad , @raj-uimatic I did this

**Comment by ElenaRad** [comment]
Thank you!!
