### ISSUE TITLE
Set-up Wizard Fix

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#346]
* [x] The set-up wizard is for new customers only, now it is working for both.... that is not correct.

**Comment by raj-uimatic** [comment]
@andypotanin Freemius will be displayed for both old and new users or just the new users (similar to assistant ) ?

**Comment by ElenaRad** [comment]
@raj  old customers should only see the first slide of setup wizard - freemius setup

**Comment by ElenaRad** [comment]
* [x] When clicking on View properties on the below screen, no properties are created. 

![image](https://cloud.githubusercontent.com/assets/19193013/20749819/91a801ba-b6fc-11e6-91e8-4772163ca6e0.png)

![image](https://cloud.githubusercontent.com/assets/19193013/20749842/ae1dd798-b6fc-11e6-9e3f-f2a210c20859.png)

**Comment by andypotanin** [comment]
@raj-uimatic elena may have already answered this:

> Freemius will be displayed for both old and new users or just the new users (similar to assistant ) ?

If possible we should let Freemius decide when it should be displayed. I assume they must have logic for this. So if they do, we should just trust Freemius to display when it thinks it needs to. For our setup wizard - **do not show it for users who are legacy users and for whom Freemius does not plan on displaying**, meaning if there are no "slides" to show in Setup Wizard, dont show it at all - basically a silent upgrade.

**Comment by raj-uimatic** [comment]
For existing users freemius screen will be shown like this : http://prntscr.com/ddocsy
For new users complete wizard as http://prntscr.com/ddodkg

**Comment by ElenaRad** [comment]
Maybe its just me, but the only difference I see is that I do not think that we should overlap the pins in the bg with text. 

![image](https://cloud.githubusercontent.com/assets/19193013/20765355/9eea4200-b73a-11e6-9a47-ef6e2e02bf8f.png)

**Comment by ElenaRad** [comment]
Also, I am not sure but every time I go through the steps, no test properties are created.  (Can't show screenshot as all my sites are down :( 

Please check in the AM.

**Comment by ElenaRad** [comment]
@raj-uimatic 

* [x] Please remove the icons and just format the buttons so they look good, maybe make them a bit bigger. Once you change styles, send me the screenshot for approval. 

![image](https://cloud.githubusercontent.com/assets/19193013/20828808/e4dbbb8e-b881-11e6-9e09-cf986803db61.png)

**Comment by raj-uimatic** [comment]
@ElenaRad  something like this ?

http://prntscr.com/dfi224

**Comment by andypotanin** [comment]
@raj-uimatic where does "Skip this step" go?

**Comment by raj-uimatic** [comment]
@andypotanin to the WP dashboard.

**Comment by andypotanin** [comment]
@raj-uimatic and the first option goes to the new "default properties" page created on the front-end?

**Comment by raj-uimatic** [comment]
@andypotanin  previously went to frontend (default properties), now takes to the Backend(All properties)

**Comment by andypotanin** [comment]
@raj-uimatic hm. I feel like having it either go to All Properties (admin) or Dashboard (admin) isn't very useful. At least using the term "skip this step" doesn't really make sense because it's not really a step being skipped. 

I think if we want to have two options it should be either - 
1. go to admin and see/edit properties
2. go to frontend and see what things look like there

What do you think?

**Comment by raj-uimatic** [comment]
@andypotanin 
1. This one is in place, I feel it will be better if we position it second rather than first.
2. This was originally there and will be a better choice definitely. (maybe move it back to first place ie is left-side button)

**Comment by raj-uimatic** [comment]
In a nutshell
Button 1 goes to frontend properties page
Button 2 goes to "all properties" in the backend, for the admin to edit/see properties.

**Comment by andypotanin** [comment]
@raj-uimatic that seems like a better way to do it, but if there are other things to tweak we can put this off for a day or so. @ElenaRad will be demonstrating this to @ewsopp and myself sometime today to show us progress, and which point we will probably get some feedback from @ewsopp who is going to be looking at this with fresh eyes and may be able to give us some new ideas/feedback.

You should probably be on the call as well, please coordinate with @ElenaRad

**Comment by Mashenka** [comment]
- [ ] error when tried to click on Properties menu after I went all steps
![image](https://cloud.githubusercontent.com/assets/5111163/21193350/ae605d82-c234-11e6-878f-f42ca49acb4e.png)

**Comment by Mashenka** [comment]
Some notes:
- [ ] Layout should exclude ability to use template on single property page, so that part should be hidden when layouts enabled.

But if the layouts not enabled there should be still ability to use that options

![image](https://cloud.githubusercontent.com/assets/5111163/21196371/0dd03bb0-c240-11e6-9fdc-40b9db956184.png)

**Comment by Mashenka** [comment]
Some notes:
- [x] Layout should exclude ability to use template on single property page, so that part should be hidden when layouts enabled.

But if the layouts not enabled there should be still ability to use that options

![image](https://cloud.githubusercontent.com/assets/5111163/21196371/0dd03bb0-c240-11e6-9fdc-40b9db956184.png)
 

- [ ] where is ability to open set up wizard again? Did we delete it?

- [ ] on last step, this is not clear that links will go to the backend or frontend to overview properties. Also there should be link to single property page.

**Comment by raj-uimatic** [comment]
@Mashenka 

> "error when tried to click on Properties menu after I went all steps" 

You have to exit the setup-wizard by clicking one of the two buttons at the end. Till that time "Freemius" disables direct access to any of the plugin pages. Hence the error.

**Comment by raj-uimatic** [comment]
@Mashenka 

> **" where is ability to open set up wizard again? Did we delete it?"**

Setup wizard button appears at the top on the settings page and logic is still same :
-> old installs will just see "freemius" screen [no button for relaunching wizard ]
-> new installs will see complete wizard and also the "Button" on the settings page to relaunch wizard.
It might be an error. Can you tell me more details about your installation on which you tested.
Did the install previously had a wp-property plugin (which you removed and reinstalled) or was it on a fresh website ?

**Comment by raj-uimatic** [comment]
@Mashenka 

> ** on last step, this is not clear that links will go to the backend or frontend to overview properties. **

I think we can change labels to make them more obvious. Any suggestions ?

> ** Also there should be link to single property page. ** 


This was removed during the last set up updates 
https://github.com/wp-property/wp-property/issues/235#issuecomment-262817958

**Comment by Mashenka** [comment]
@andypotanin why did we removed link to single property page - https://github.com/wp-property/wp-property/issues/346#issuecomment-264835216

**Comment by Mashenka** [comment]
@raj-uimatic 

1.  reagarding this https://github.com/wp-property/wp-property/issues/346#issuecomment-267238418
need to be more userfriendly. Can we add ability to click where user want or make wizard fullscreen

2.  reagarding this https://github.com/wp-property/wp-property/issues/346#issuecomment-267239098
I have tested on local site. Wp-property was installed there before, but I'm creating new database every time. And I wasn't able to open wizard again.

3.  > ** on last step, this is not clear that links will go to the backend or frontend to overview properties. **

we need to have some explanation what users will see on those pages. View Properties on Backend and View Properties on Frontend.

Also I believe we should have something like, That's all you can check demo properties using these links

**Comment by ElenaRad** [comment]
@raj-uimatic 

* [x] If the below screen is the final step, we might want to get rid of the next arrow: 

![image](https://cloud.githubusercontent.com/assets/19193013/21229039/e0c5c41a-c2e8-11e6-8d5d-7e0d7047bf93.png)

**Comment by raj-uimatic** [comment]
@Mashenka 

> we need to have some explanation what users will see on those pages. View Properties on Backend and View Properties on Frontend.

Seems I named both buttons same. Fixed now !

> I have tested on local site. Wp-property was installed there before, but I'm creating new database every time. And I wasn't able to open wizard again.

Trying to replicate this error

**Comment by Mashenka** [comment]
>I have tested on local site. Wp-property was installed there before, but I'm creating new database every time. And I wasn't able to open wizard again.

Can't replicate any more on live enviroment
