### ISSUE TITLE
Fix Swiper in WWP

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#348]
* [ ] Swiper is not working in wpp, please fix. 

![image](https://cloud.githubusercontent.com/assets/19193013/20758344/294418c2-b722-11e6-8d6a-2089eeda1ed9.png)

**Comment by ElenaRad** [comment]
Reference this:  https://usabilitydynamics-www-exceedrealty-net-develop-den.c.wpcloud.io/properties/single-family-in-cobblestone-creek-houston/

**Comment by alimuzzaman** [comment]
There is a child theme installed on that site called "exceedrealty". I need that.

**Comment by ElenaRad** [comment]
Exceedrealty is actually a project I am working on, its a name of the customer not a theme.

**Comment by Mashenka** [comment]
@ElenaRad can you be more exact what is not working there

**Comment by ElenaRad** [comment]
all set
