### ISSUE TITLE
Fix Property Map/"Get Directions" link duplicate

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#353]
* [ ] Get rid of the extra "Get Directions" link on property map? 

![image](https://cloud.githubusercontent.com/assets/19193013/21101267/fc4953f6-c080-11e6-8d21-fb3410d171c9.png)

**Comment by margarette13** [comment]
I have the same issue.Is this issue been resolved? thanks.

**Comment by Mashenka** [comment]
@margarette13 what theme do you have?

**Comment by margarette13** [comment]
I am using Real Estate 7 by contempo.

**Comment by margarette13** [comment]
I am using Real Estate 7 by contempo.

**Comment by Mashenka** [comment]
That issue will be fixed in next release - https://github.com/wp-property/wp-property/issues/519

**Comment by margarette13** [comment]
Okay Thank you so much.
