### ISSUE TITLE
Layout's style issues - Single property page

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#364]
theme 2016:
https://themebox.uds.io/twentysixteen/properties/lot-land-in-5th-8/
- [x] simple list in Property Details has bullets
![image](https://cloud.githubusercontent.com/assets/5111163/21437252/79e32f64-c88b-11e6-8b2a-9194c5bc4b38.png)
 - [x]  Agents widget
![image](https://cloud.githubusercontent.com/assets/5111163/21453808/a6e8f06c-c91b-11e6-979b-c2d96bf86c25.png)

- [x] a lot of space between terms
![image](https://cloud.githubusercontent.com/assets/5111163/21453861/5457589c-c91c-11e6-808e-e1eefdf96da7.png)

- [ ] do we have ability make this gallery smarter? make it 100% width?
![image](https://cloud.githubusercontent.com/assets/5111163/21453958/1145634a-c91d-11e6-96d3-bd39874738ce.png)

**Comment by Mashenka** [comment]
Theme Enfold

- [ ] agents widget not showing at all

**Comment by SoSeductive** [comment]
Gallery has only static width and height, we cant do 100% width and auto height. for it i think need write new settings and scripts

**Comment by Mashenka** [comment]
Theme Enfold

- [x] agents widget shows array 
https://themebox.uds.io/enfold/properties/residential-in-sherrill-point/

- [x] featured image is broken
![image](https://cloud.githubusercontent.com/assets/5111163/21519383/4456ef34-ccf5-11e6-92e2-36fd50803b44.png)


Theme Divi, X-theme, Enfold and all other except 2016

- [x] content is not showing
https://themebox.uds.io/divi/properties/residential-in-leatherwood/
https://themebox.uds.io/x-theme/properties/lot-land-in-28th-5/
https://themebox.uds.io/enfold/properties/residential-in-sherrill-point/

- [x] these buttons(prev/next property). they are not ours. but can we also style them?
https://themebox.uds.io/spacious/properties/residential-in-3rd-5/
![image](https://cloud.githubusercontent.com/assets/5111163/21519819/b4fffa02-ccf8-11e6-97d8-2d414cdc602a.png)

- [x] agent image link is broken. I have reuploaded several times
https://themebox.uds.io/karma/properties/residential-in-18th-4/
![image](https://cloud.githubusercontent.com/assets/5111163/21520125/bd504f52-ccfa-11e6-9833-c591d1717977.png)

**Comment by Mashenka** [comment]
Links to check single property pages in different themes:

2016 - https://themebox.uds.io/twentysixteen/properties/lot-land-in-5th-8/
Divi - https://themebox.uds.io/divi/properties/residential-in-leatherwood/
X-theme - https://themebox.uds.io/x-theme/properties/lot-land-in-28th-5/
Enfold - https://themebox.uds.io/enfold/properties/residential-in-sherrill-point/
spacious  - https://themebox.uds.io/spacious/properties/residential-in-cornwallis-2/
Karma - https://themebox.uds.io/karma/properties/residential-in-18th-4/

**Comment by Mashenka** [comment]
@ElenaRad I have checked till Karma theme. Check single property layout on other themes

**Comment by SoSeductive** [comment]
When content not showin you need to activate SiteOrigin Widgets Bundle
