### ISSUE TITLE
“gallery could not load” error on Mobile(tested on iPhone)

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#38]
For mobile version, I am getting “gallery could not load” error.

After clicking on any listing here, the gallery doesn’t load on iPhone in Safari:

![image](https://cloud.githubusercontent.com/assets/1255935/3570380/cb12917e-0b4e-11e4-8d45-0f98b7491a8e.png)

In this case do not working [property_gallery], but [property_gallery carousel=false] works.
[property_slideshow] also doesn't work correctly on mobile(ios)

This task is also duplicated in Active Collab. - https://projects.usabilitydynamics.com/projects/wp-property-1377/tasks/204

Premium request - https://usabilitydynamics.com/products/wp-property/forum/topic/gallery-not-working-on-responsive-view/

**Comment by pemaxim** [comment]
I can not replicate the issue.
Looks like, it's related only to client's theme.
The Denali and default WP thems do not have this issue.
