### ISSUE TITLE
Allow the use of slashes in attribute fields

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#382]
https://workspace.uds.io/wp-admin/post.php?post=749632&action=edit

* [ ] Attribute fields do not allow / \ to be used in the data entry fields.

![image](https://cloud.githubusercontent.com/assets/19193013/22342845/772ad3d8-e3fe-11e6-96c1-806ee83b1f03.png)

**Comment by ewsopp** [comment]
Why?

**Comment by ElenaRad** [comment]
Customers want to be able to add types/attributes such as big lots/small lots. This is not the first customer asking about this, so figured it would be helpful if we add this.

**Comment by Mashenka** [comment]
@ewsopp  also property types with slashes are coomon types from RETS

**Comment by andypotanin** [comment]
@ElenaRad this may be possible with `latest` version which creates all property types as terms. The slug will not be able to have slashes in it but the title should.

That being said, we have standard property types now so adding new ones will be discouraged.
