### ISSUE TITLE
Internet Explorer 11. WP-Property settings can't be saved.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#383]

**Comment by andypotanin** [comment]
@Mashenka please see if this can be replicated on `latest` after @alimuzzaman's updates.

**Comment by alimuzzaman** [comment]
@Mashenka What is the problem. I got internet explorer unresponsive when I hit save. Is that or js error.

**Comment by Mashenka** [comment]
yes, unresponsive

**Comment by Mashenka** [comment]
@alimuzzaman with your latest fix do not see that issue any more.
