### ISSUE TITLE
Layouts  issues

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#386]
- [x] here should be 3 overview layouts, not terms, I have created new category and layouts here  https://themebox.uds.io/twentysixteen/wp-admin/edit.php?post_type=wpp_layout

- [x] Default properties page should apply one of Overview layouts. 
Same layout should apply search results page and terms results page

- [x] there shouldn't be option "No Layout"

- [x] there shouldn't be option to add new category. And visually also

- [x] layouts update issue - https://github.com/wp-property/wp-property/issues/368

- [x] option default property page should be selected

**Comment by Mashenka** [comment]
@ElenaRad add 3 layouts for Overview or choose from what we have and rename. we need 3 only.

**Comment by Mashenka** [comment]
- [x] on new site there should be added default categories single property and property overview

- [x] Page builder should be enabled by default. We need to recommend that plugin, like this
![image](https://cloud.githubusercontent.com/assets/5111163/23173532/21224160-f862-11e6-9767-1c7a0ea5c139.png)

- [x] there should be option to choose layout in order to edit, like this - 
![image](https://cloud.githubusercontent.com/assets/5111163/22993915/74af2d64-f3cd-11e6-8371-6075031e0a6d.png)

- [x] page.php should be set up by default 
![image](https://cloud.githubusercontent.com/assets/5111163/22993972/b350cd0c-f3cd-11e6-9165-cb51d95e8bb2.png)

- [x] there should be new taxonomy with term "Available in API" based on site API key. So for those who in white list there will be ability to post layouts to API. 

- [x] Preview button on edit Layout screen.

- [x] Warning if user didn't choose category preventing to publish. 
"You need to choose category of your layout before publish it" 

- [ ] 2017 theme do not have styles - https://themebox.uds.io/demo/

**Comment by Mashenka** [comment]
- [x] when layouts disabled there should be old options about property.php page in settings/main tab. 
and template should be applied

**Comment by SoSeductive** [comment]
We cant add button with choose layout in order to edit, because this panel was hardcoded in php file and have no hooks. I am not yet found a solution. I Try to do it some later

**Comment by andypotanin** [comment]
@Mashenka Some of your above comments/subtasks should be in https://github.com/wp-property/wp-property-layouts, not here.

**Comment by andypotanin** [comment]
> We cant add button with choose layout in order to edit, because this panel was hardcoded in php file and have no hooks. I am not yet found a solution. I Try to do it some later
@SoSeductive If you're talking about this:
![image](https://cloud.githubusercontent.com/assets/1255935/23152351/801ca202-f7cf-11e6-8fe5-50f1ee6ca4f3.png)
Then you should know that SiteOrigin has a pretty simple API for loading pre-made SiteOrigin layouts from an API.

**Comment by Mashenka** [comment]
- [x] double option

![image](https://cloud.githubusercontent.com/assets/5111163/23310512/7b003948-fabb-11e6-8a6b-f186a309300f.png)

**Comment by Mashenka** [comment]
Can we change that for WP-Property Layouts? -

![image](https://cloud.githubusercontent.com/assets/5111163/23359149/8bf7a9fa-fced-11e6-8a3c-c61c8f210994.png)

**Comment by SoSeductive** [comment]
i have no find a hook to change it. in code title have no filters

**Comment by andypotanin** [comment]
@SoSeductive we could instead show our layouts under "Layout Directory" and leave "Theme Defined" for layouts that really are defined by themes - perhaps some of our themes will have special layouts?

**Comment by SoSeductive** [comment]
@andypotanin i think we cant do this, because Page Builder has only one filter for adding custom layouts, only in "Theme Defined" tab. And we cant create new tab, because PB do not have filters for it.

**Comment by andypotanin** [comment]
@SoSeductive I explained to you how to do this by re-defining the admin ajax endpoint the other day.

**Comment by Mashenka** [comment]
- [x] if layouts enabled there should be some layouts by default set up - https://themebox.uds.io/demo/properties/nice-property/

**Comment by SoSeductive** [comment]
@andypotanin I did it, but I had to use `add_action`. I think it is not so good idea..

**Comment by andypotanin** [comment]
@SoSeductive that's the only way to do it if they don't have a filter. Its not extremely elegant but it seems to work. See what @pemaxim says.

**Comment by andypotanin** [comment]
@Mashenka @SoSeductive 

I've reworked on the UI and workflow. For now focus should be on working with local layouts, not publishing to API.

![image](https://cloud.githubusercontent.com/assets/1255935/23541511/d4e00700-ffb5-11e6-9cc9-c6e87968be9a.png)

![image](https://cloud.githubusercontent.com/assets/1255935/23541538/0d2b806c-ffb6-11e6-95aa-eacccd9507e7.png)

![image](https://cloud.githubusercontent.com/assets/1255935/23541550/21e50d34-ffb6-11e6-83db-48ce65531394.png)

![image](https://cloud.githubusercontent.com/assets/1255935/23541570/4b883e7c-ffb6-11e6-9c14-d13fe0878b02.png)

**Comment by Mashenka** [comment]
@andy did you also delete preview link?

**Comment by andypotanin** [comment]
No. What is that?

**Comment by Mashenka** [comment]
sorry, found

**Comment by Mashenka** [comment]
@andypotanin why we do nothave layouts from API here - 
![image](https://cloud.githubusercontent.com/assets/5111163/23547992/216fbe28-000e-11e7-859a-e4e34e591270.png)
