### ISSUE TITLE
Warnings on Single Child Properties pages

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#39]
If property has parent - http://screencast.com/t/bdQ0bMBz2
http://screencast.com/t/7MitqAhW9T

on Active Collab - https://projects.usabilitydynamics.com/projects/wp-property-1377/tasks/185

**Comment by andypotanin** [comment]
Yes, we're trying to clean these up, but most WordPress sites will always have some warning. They are mostly harmless and should not be displayed on production sites. Should be configured in wp-config.php. See https://codex.wordpress.org/Editing_wp-config.php#Debug
