### ISSUE TITLE
Unique taxonomies not showing on frontend

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#397]
We have such logic in our template - https://github.com/wp-property/wp-property/blob/latest/static/views/property.php#L115

![image](https://cloud.githubusercontent.com/assets/5111163/23228504/6ebfcd32-f945-11e6-9ac3-d2cbd81e562b.png)

![image](https://cloud.githubusercontent.com/assets/5111163/23228541/8f4590e6-f945-11e6-8683-c24ebe2706d8.png)

Test property - https://workspace.uds.io/properties/18-greentrees-road-terenure-dublin-12/

**Comment by andypotanin** [comment]
@Mashenka We'll deal with this once Layouts are done and we start working on configuring front-end elements/widgets.

**Comment by Mashenka** [comment]
@pemaxim @andypotanin what we will decide? Why do we hide unique terms?

**Comment by andypotanin** [comment]
@Mashenka they should display on the front-end the same way regular attributes (meta) does. They should be treated as meta fields from the front-end, even though are stored in terms.
