### ISSUE TITLE
Feedback: Featured properties shortcode displays "extra" invalid div

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#40]
Need to be checked

in the property-featured-shortcode.php template, you need to remove the array key "total" from the $properties variable, otherwise the template will display an empty div (visible in the twentyten theme, for instance).

If you add: 
unset($properties['total']); 
just before the loop: 
foreach($properties as $featured):
That will do the trick. The total count is not necessary to iterate anyways ;)
http://screencast.com/t/wFNDIHBG

https://projects.usabilitydynamics.com/projects/wp-property-1377/tasks/60

**Comment by pemaxim** [comment]
I did not find the issue in code. Probably it was fixed before. However, be sure that the issue is related to WP-Property default templates, but not to Denali or Madison themes.
