### ISSUE TITLE
Absent default Property Types on fresh WP-Property installation

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#406]
New user, who just installed WP-Property first time will not be able to update any option on Settings page, because we required at least one Property Type defined! But 'Add Row' is broken when there is no any existing row.....

![image](https://cloud.githubusercontent.com/assets/308489/23501930/9ca5808a-ff3e-11e6-82f5-2d024e4c322c.png)

**Comment by pemaxim** [comment]
There is no any default Taxonomy as well. And it can not be added......

![image](https://cloud.githubusercontent.com/assets/308489/23502139/682f9ea2-ff3f-11e6-9276-23ceee889d15.png)

**Comment by pemaxim** [comment]
@alimuzzaman @Mashenka 
I see that we have default property types, but they are not being rendered in UI.
I believe it's related to the JS error:

![image](https://cloud.githubusercontent.com/assets/308489/23502502/c15ab8f8-ff40-11e6-9212-009868ddc463.png)

**Comment by Mashenka** [comment]
@pemaxim @alimuzzaman Replicated with latest branch. Still can't replicate with released version.

**Comment by andypotanin** [comment]
@pemaxim we could enable the Setup Assistant. It will load the default/standard Types and fields. Could be the simplest solution. It should only run on truly new installs though.

**Comment by alimuzzaman** [comment]
@pemaxim  That was me. Sorry. It should work now.
