### ISSUE TITLE
Child property does not display inherited from property attribute value with multi-checkbox

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#407]
* [ ] When creating an attribute with the data entry as Multi-checkbox appears as "array" on child properties: 

https://usabilitydynamics-sandbox-uds-io-elena.c.rabbit.ci/properties/parent-building/unit-45/

![image](https://cloud.githubusercontent.com/assets/19193013/23513590/332bd436-ff6d-11e6-99f0-475e1ceacdae.png)

![image](https://cloud.githubusercontent.com/assets/19193013/23513620/49eddbc4-ff6d-11e6-983b-6a3df9aa5bdb.png)

![image](https://cloud.githubusercontent.com/assets/19193013/23513634/60d1b040-ff6d-11e6-9080-56622a07563d.png)

![image](https://cloud.githubusercontent.com/assets/19193013/23513648/715e90c2-ff6d-11e6-8495-d1858b819004.png)

**Comment by SoSeductive** [comment]
@Mashenka Can't repeat issue
