### ISSUE TITLE
Ensure Terms are Not Inserted if Same Value Exists

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-property#409]
To avoid this issue:
![image](https://cloud.githubusercontent.com/assets/1255935/23523284/43da175c-ff54-11e6-9f66-9415e4fc8596.png)

Lets make sure that a term value/meta has changed before updating/inserting it.

**Comment by andypotanin** [comment]
@pemaxim Also, do a brief analysis of the `wp_termmeta` data, to make sure we're not storing too much extra information. For instance, we seem to record `_id` twice:

![image](https://cloud.githubusercontent.com/assets/1255935/23560191/968c743c-0007-11e7-8ae2-578c9a67d026.png)

Perhaps there are other meta fields that we could ignore. 

For example, we store `categorical-parent_term_id`, `categorical-parent_slug` and `categorical-parent_name`, which are only passed to create the parent of a term if it does not exist. I don't know if we actually need to store these fields since the parent relationship is stored in `wp_term_taxonomy` table. 

![image](https://cloud.githubusercontent.com/assets/1255935/23560307/f4de0b22-0007-11e7-9edf-716272b4d8b7.png)

**Comment by Mashenka** [comment]
moved to correct repository
