### ISSUE TITLE
New Address Field and Logic

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-property#411]
The new input address field should be `wpp_address`. It used be configurable and any field could be used, but now it's fixed as `wpp_address`. The value of `wpp_address` is geocoded.

* [ ] Update UI to make sure it works with `wpp_address`. 
* [ ] Remove Settings UI for "Attribute to use for physical addresses".
* [ ] Update our geolocation to work with the new naming conventions.
* [ ] Setup Google API key to be provided by setup assistant. (Expires every 7 days or so)

**Comment by Mashenka** [comment]
moved to correct repository - https://github.com/wp-property/wp-property-terms/issues/32
