### ISSUE TITLE
when activating wp-property on new site only add-ons  tab showing

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#413]
when clicking on properties other appear

![image](https://cloud.githubusercontent.com/assets/5111163/23558475/73b5197a-003c-11e7-984b-f26fc0355532.png)

**Comment by pemaxim** [comment]
@Mashenka fixed. The bug was related to custom WP-Property capabilities. It occurred ONLY on first plugin activation and never happened on next page loads ( re-activations, etc ).
