### ISSUE TITLE
Store js localization file as attachment

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#414]
We have the issue with [js localization file](https://github.com/wp-property/wp-property/blob/latest/lib/class_core.php#L1363-L1387) ( it's being queued [js localization file](https://github.com/wp-property/wp-property/blob/latest/lib/class_core.php#L1363-L1387) ) when [WP-Stateless](https://github.com/wpCloud/wp-stateless) plugin is being used. Also, the current solution may cause other different issues.

* [x] Be sure that WPP is using `cache_dir` and `cache_url` [logic](https://github.com/wp-property/wp-property/blob/latest/lib/class_core.php#L1363-L1387) only for [js localization file](https://github.com/wp-property/wp-property/blob/latest/lib/class_core.php#L1363-L1387) today. If not, let @pemaxim know about it. In other case, continue with subtasks below:
* [ ] Create [js localization file](https://github.com/wp-property/wp-property/blob/latest/lib/class_core.php#L1363-L1387) as attachment. You may add option to know which attachment belongs to the file. 
* [ ] Be sure, that attachment is being flushed every time on [cache clearing](https://github.com/wp-property/wp-property/blob/latest/lib/class_functions.php#L3117-L3132) Today, we remove [js localization file](https://github.com/wp-property/wp-property/blob/latest/lib/class_core.php#L1363-L1387) on clearing the cache. So we should have the similar behaviour for attachment.
* [ ] Get rid of `cache_dir` and `cache_url` logic since it will not be used anymore

**Comment by alimuzzaman** [comment]
@pemaxim Please explain "You may add option to know which attachment belongs to the file.". I added two link after "Clear Cache" button.
I have added cache dir on WP CRM previously for js localization file.

**Comment by alimuzzaman** [comment]
@Mashenka Should I make any changes?

**Comment by pemaxim** [comment]
> Please explain "You may add option to know which attachment belongs to the file.". 

@alimuzzaman It's what you already did by adding option: `get_option('wp-property-l10n-attachment');`

**Comment by pemaxim** [comment]
@alimuzzaman 

![image](https://cloud.githubusercontent.com/assets/308489/24904815/5914f8d2-1eba-11e7-89f9-61b8238f6f02.png)

**Comment by pemaxim** [comment]
@alimuzzaman Check my comments here: https://github.com/wp-property/wp-property/commit/ef62b55acbb56080479f001ae6dfc6f0245f3863

**Comment by alimuzzaman** [comment]
@pemaxim I have updated the code as you requested. Have some trouble with WP Sateless.

**Comment by Mashenka** [comment]
@andypotanin should I close that? It seems we abandon that idea

**Comment by andypotanin** [comment]
@Mashenka No idea. Check with @pemaxim and @alimuzzaman since they worked on this.

**Comment by Mashenka** [comment]
@pemaxim @alimuzzaman do you remember, did we abandon that idea?

**Comment by alimuzzaman** [comment]
It was I and @andypotanin to abandon this idea. As this creates unnecessary complexity.

**Comment by alimuzzaman** [comment]
As the file is small there wasn't much benefit.
