### ISSUE TITLE
QA 2.3

### ISSUE THREAD

**Issue by pemaxim** [wp-property/wp-property#418]
#### General

* [x] Did we disable Welcome WP-Property messages on first install and upgrades? Why?
* [x] Did we disable all WP-Property messages such as system Warnings/Notices/Errors ?
* [x] Integrated Agents feature bugs: no permissions to add new Agent, not shown list of Agents. Note, Agents plugin (add-on) must not be activated.

#### Settings page

* [ ] Did we disable legacy Meta? We did not want to move it to attributes to not break already existing users sites, because meta had separated logic. For example, we have Tagline meta which is included to our legacy templates, we use meta attributes in PDF Flyers , etc... If we want to move it to attributes (whatever else) we must use feature flag for it and be sure that it will not be enabled for already existing sites.
* [x] We have missing option "Enable Legacy Features" in Advanced Options on Main tab ( deprecated features will be enabled. E.g.: Child Properties and Featured Properties Widgets, etc ). Is it removed completely? I think it should be enabled for already existing sites.
* [ ] We have missing option "Enable 'Falls Under' deep depth " in Advanced Options on Main tab (  Allows to set child Property as parent. ). Is it removed completely? I think it should be enabled for already existing sites.
* [x] Sort by Groups does not work on Developer Tab

#### Edit Property page

* [x] Falls Under option disappeared
* [x] Property Type option disappeared

## Front End

**Comment by pemaxim** [comment]
The current list of feature flags for particular QA:

![image](https://cloud.githubusercontent.com/assets/308489/23699184/e2c4459e-03f6-11e7-9712-e536974a0a8c.png)

**Comment by Mashenka** [comment]
- Regarding  Meta, Agree with you. I also think is should be transferred to textarea attributes. PDF didn't not support it.

- Enable  'Falls Under' deep depth now in each property type

- Still  see property type on edit page - https://workspace.uds.io/wp-admin/post.php?post=775686&action=edit

- "Enable Legacy Features" I agree that is should be reverted.

- also I see warnings about licensees. try to deactivate and activate plugin.

**Comment by Mashenka** [comment]
- [ ]  issue on fresh install. Single property page do not have default template. layouts disabled
![image](https://cloud.githubusercontent.com/assets/5111163/23805949/8d70d494-05c8-11e7-8452-40b977d09d7b.png)
![image](https://cloud.githubusercontent.com/assets/5111163/23805956/91dca9cc-05c8-11e7-95ad-45d09bf3b7d9.png)

**Comment by Mashenka** [comment]
- [ ] when activating madison theme
Warning: preg_replace() [function.preg-replace]: Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u at offset 14 in Z:\home\latest\www\wp-content\themes\wp-madison\vendor\usabilitydynamics\lib-wp-bootstrap\lib\classes\class-utility.php on line 74
![image](https://cloud.githubusercontent.com/assets/5111163/23806114/1fa88dac-05c9-11e7-91d9-131a72ef811e.png)

- [ ] supermap not showing properties shortcode [supermap price=all property_type=all]
![image](https://cloud.githubusercontent.com/assets/5111163/23806625/0f41ffdc-05cb-11e7-8a70-f339fd0cd247.png)

![image](https://cloud.githubusercontent.com/assets/5111163/23806696/50ed5850-05cb-11e7-9f3a-41b7f103be0a.png)

**Comment by Mashenka** [comment]
- [ ] at the moment there is no server and browser API key. It seems there only one for both
![image](https://cloud.githubusercontent.com/assets/5111163/23908036/807513ac-08db-11e7-9976-8f40fa96f1ec.png)

**Comment by Mashenka** [comment]
- [ ] it seems it was fixed in latest branch of agents -
[agent_card user_id=2]

![image](https://cloud.githubusercontent.com/assets/5111163/23996501/4b81c09c-0a56-11e7-8b6a-d51c4cd5dc88.png)

 Notice: Use of undefined constant full_bio - assumed 'full_bio' in Z:\home\latest\www\wp-content\plugins\wp-property\lib\features\wp-property-agents\lib\class-agents.php on line 1954

@pemaxim did you merge agents from latest branch?

**Comment by SoSeductive** [comment]
- [x] on fresh install on "Add Property" page
![1212](https://cloud.githubusercontent.com/assets/2156026/24758262/86b3fbea-1aea-11e7-8f9a-fda8e5e2a070.png)
