### ISSUE TITLE
Option Show larger image of Property when image is clicked using fancybox.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#42]
Option "Show larger image of Property when the image is clicked using fancybox." does not work on supermap
![image](https://user-images.githubusercontent.com/5111163/41645310-44aa4f76-7479-11e8-8d63-a795fa52d5bf.png)

Topics:
https://usabilitydynamics.com/products/wp-property/forum/topic/maps-breaking-responsive-site/
https://usabilitydynamics.com/products/wp-property/forum/topic/wp-property-supermap-changing-image-link/

**Comment by pemaxim** [comment]
I can not replicate the issue. It works for me. Tested in:
- browsers: FireFox, Chrome
- Themes: Denali, TwentyTwelve

**Comment by Mashenka** [comment]
And I can replicate on Denali theme even if option "Show larger image of Property when image is clicked using fancybox." enabled.

**Comment by Mashenka** [comment]
Moved to correct repository
