### ISSUE TITLE
WPML - cannot access single property

### ISSUE THREAD

**Issue by srdjan-jcc** [wp-property/wp-property#425]
If Default Properties Page is set to existing page,
single property is not found (404 error) on other language.

permalink structure: 'Day and name'

1. Install WP Property and WPML (2 languages)
2. Save permalinks
3. Add property and duplicate it to other language
4. Set Sample Page to be default properties page
Properties > Settings > Main > Default Properties Page
5. Try accessing single product on frontend in other language (404)
//localhost/sample-page/%product_name%

**Comment by Mashenka** [comment]
@srdjan-jcc you should notice that latest branch do not have such option as Default Property page. It can be only specific page now.

Without that option can't replicate your issue.
https://workspace.uds.io/properties/5-rena-hobson-court-address/

**Comment by srdjan-jcc** [comment]
@Mashenka Yes, noticed now.
Issue is same with latest branch.

**Comment by Mashenka** [comment]
which issue?  I can't replicate because there is no such option any more. I have provided link where WP-Property and WPML set up.

**Comment by srdjan-jcc** [comment]
@Mashenka OK I re-tested.
I can replicate issue with single property on other language.
Do you want me to edit issue description (steps to reproduce)?

**Comment by Mashenka** [comment]
yes , please provide steps again

**Comment by srdjan-jcc** [comment]
@Mashenka I edited description and steps to reproduce.
I guess that page slug is not matched so 404 error occurs.

Is there a way to adjust product page slug according to language?

**Comment by Mashenka** [comment]
here is my settings, I followed your steps, I can also give you access to that test site, because I can't replicate that

![image](https://cloud.githubusercontent.com/assets/5111163/24005234/21019854-0a71-11e7-8853-6b5afd126473.png)

https://workspace.uds.io/ru/sample-page/russian-property/

**Comment by srdjan-jcc** [comment]
@Mashenka Can you please rename Russian page title and slug to:
sample-page-ru and try again?
I think 404 not occurring if page slugs are same.

**Comment by Mashenka** [comment]
@srdjan-jcc I have added account for you on that site. Please show me the issue.

**Comment by srdjan-jcc** [comment]
@Mashenka I cannot replicate issue on your test site.
At my local, whatever I do - I get 404 error on single property.
Tried with same setup as I saw on your test site :(

**Comment by Mashenka** [comment]
@srdjan-jcc let me know if you need anything else from me
