### ISSUE TITLE
Automatic Scroll on backend and frontend overview

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#43]
When hitting next on the backend and front-end. it should scroll to top automatically
it does it on Firefox. But doesn’t work on Chrome and Opera 
https://usabilitydynamics.zendesk.com/agent/#/tickets/383

**Comment by andypotanin** [comment]
Listing table completely revised in v2.0, verify that it resolves this, please.

**Comment by Mashenka** [comment]
Still Exist in WP-Property 2.1.2

**Comment by andypotanin** [comment]
@Mashenka need WorkSpace URLs that demonstrate the problem.

**Comment by Mashenka** [comment]
http://workspace.uds.io/wp-admin/edit.php?post_type=property&page=all_properties

**Comment by andypotanin** [comment]
What exactly do you mean by "next"?

**Comment by Mashenka** [comment]
Just go to the bottom and click to go to the next page of properties, you should be redirected on the top of next page
