### ISSUE TITLE
Blank Pop-Up on Add-ons page (dashboard)

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#437]
- [x]  If you go to Properties/Add-ons/ More Products Tab you will get a list of all out add-ons related to the plug-in, however when you click on Product Image (highlighted in red squares) you get an emp[ty fancy box: 

![](https://content.screencast.com/users/ElenaRadc/folders/Jing/media/bb576448-e83e-4274-85fa-398942ba1fd6/2017-04-18_1817.png)

![](https://content.screencast.com/users/ElenaRadc/folders/Jing/media/6fa85ae9-cddf-4f9d-8e30-91c6cbafea41/2017-04-18_1816.png)

P.S: This problem appears on all plug-ins (let me know if you need an issue for each plug-in)

**Comment by SoSeductive** [comment]
@ElenaRad I removed thickbox from image and title

**Comment by ElenaRad** [comment]
@SoSeductive :  
https://workspace.uds.io/wp-admin/ ---> Having same issues on this URL 
https://sandbox-uds-io-elena.c.rabbit.ci/wp-admin/ (sandbox sites)-----> all three links go to the product page (https://www.usabilitydynamics.com/product/wp-invoice-mijireh-checkout)

- [x] make the below changes 
![image](https://cloud.githubusercontent.com/assets/19193013/25537257/74c0ad4e-2c46-11e7-8122-e53f670b397e.png)

**Comment by Mashenka** [comment]
@SoSeductive those changes already in latest?

**Comment by SoSeductive** [comment]
@Mashenka No. I did it for test for Elena on workspace

**Comment by Mashenka** [comment]
why? move please to latest

**Comment by SoSeductive** [comment]
@Mashenka Done
