### ISSUE TITLE
Themebox/Dev Tab/Attributes

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#442]
* Site: https://themebox.uds.io/ (MultiSite, there are 12 sites there, please make sure that all of them are working properly). 
* Link:  https://themebox.uds.io/wp-admin/edit.php?post_type=property&page=property_settings

- Properties/Settings/Dev Tab/Attributes: 
- [ ] "Toggle Advanced Settings" option is not working, nothing happens when you click on it. To expand, "Expand All" button should be used. 

![image](https://cloud.githubusercontent.com/assets/19193013/25631734/f2353a16-2f79-11e7-9bf6-8820a846872f.png)
![image](https://cloud.githubusercontent.com/assets/19193013/25631826/3d63c052-2f7a-11e7-9b3e-233ddb575fd2.png)

- [ ] Grouping field is not working, when clicking on the field nothing happens. When clicking on the "Sort By Groups" button, the attributes do group, however, the group field remains empty. 

![image](https://cloud.githubusercontent.com/assets/19193013/25631977/bf94786e-2f7a-11e7-8e58-dc3177ed6ce4.png)
![image](https://cloud.githubusercontent.com/assets/19193013/25632027/dde15e86-2f7a-11e7-8710-48c99467bcef.png)

**Comment by Mashenka** [comment]
wp-property issue
