### ISSUE TITLE
Themebox/Developer Tab/Taxonomies

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#443]
* Site: https://themebox.uds.io/ (MultiSite, there are 12 sites there, please make sure that all of them are working properly). 
* Link: https://themebox.uds.io/wp-admin/edit.php?post_type=property&page=property_settings

- Properties/Settings/Dev Tab/Taxonomies: 
- [ ] "Toggle Advanced Settings" option is not working, nothing happens when you click on it. To expand, "Expand All" button should be used. 
- [ ] "Type" and "Group" buttons are not working at all: 
![image](https://cloud.githubusercontent.com/assets/19193013/25633705/ba7733fc-2f80-11e7-8041-b18a4cbaac48.png)
- [ ] The slug is not working properly:
![image](https://cloud.githubusercontent.com/assets/19193013/25634130/26402124-2f82-11e7-8b57-2fcf4a6442c6.png)
- [ ]  "Manage Terms" there is no ability to add any terms: 
![image](https://cloud.githubusercontent.com/assets/19193013/25633952/96fac118-2f81-11e7-91bf-16092b212332.png)
This is what it should look like:
![image](https://cloud.githubusercontent.com/assets/19193013/25634176/45e43894-2f82-11e7-90da-90e2a37bf177.png)

**Comment by Mashenka** [comment]
@ElenaRad this is not themebox issue, but wp-property. Place issues in a correct place.
