### ISSUE TITLE
Themebox Developer Tab/Type

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#444]
* Site: https://themebox.uds.io/ (MultiSite, there are 12 sites there, please make sure that all of them are working properly). 
* Link:  https://themebox.uds.io/wp-admin/edit.php?post_type=property&page=property_settings

- [x] Types, the following buttons/functionality are not  working (Slug empty, google map marker is missing, Hidden Attributes and Inherit from Parent are not clickable): 
![image](https://cloud.githubusercontent.com/assets/19193013/25634579/ce3c3100-2f83-11e7-8228-de56232bd07e.png)

**Comment by phillipwilhelm** [comment]
Having the same issue as ElenaRad

**Comment by Mashenka** [comment]
@pwilhelm949 That issue was found not in released version, but on our testing branch. So in your case there can be issue with some third party plugin. Try to investigate and disable them one by one.
