### ISSUE TITLE
attributes were deleted

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#447]
today I update to the latest vesrion and attributes disappeared. We heard about that issue many times from user, but this is first time when that happens to me. 
https://workspace.uds.io/wp-admin/edit.php?post_type=property&page=property_settings

![image](https://cloud.githubusercontent.com/assets/5111163/25803399/4e1cf3a8-33ff-11e7-8c02-0ed11878af2c.png)

**Comment by Mashenka** [comment]
@alimuzzaman this issue appeared again. Can you add those fixes again, please. It seems someone overwrote your code.

**Comment by Mashenka** [comment]
@SoSeductive fixed

**Comment by Mashenka** [comment]
@SoSeductive move this fix to hotfix branch

**Comment by SoSeductive** [comment]
@Mashenka Reverted fixes from #447 and #448

**Comment by dcimini** [comment]
Hi all,
I have the same issue. I installed the wp-property plugin yesterday then it is updated, but I have the same issue. Can I have the patch and the instructions to install it on my wordpress?
Thank you very much
