### ISSUE TITLE
convert jQuery.live() to jQuery.on()

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#448]
- [x] wp-prperty

- [x] wp-property-slideshow

- [x] supermap

- [x]  resp slideshow

- [x] feps

- [x] walkscore

- [x] importer

- [x] pdf

- [x] facebooktabs

- [x] power tools

**Comment by SoSeductive** [comment]
@Mashenka All plugins updated in `latest` branches. I thin need to test it. Wait for feedback
