### ISSUE TITLE
Add strict search to the Property Search widget

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#45]
it also doesn't works with shortcode, such as
[property_search]
[property_overview strict_search=true]
p.s overwrite search results is disabled.

https://projects.usabilitydynamics.com/projects/wp-property-1377/tasks/93

**Comment by pemaxim** [comment]
Added strict search to [property_search] shortcode and property search widget.

http://screencast.com/t/JTc5rNen9yG

http://screencast.com/t/xa5I8GSahS
