### ISSUE TITLE
Property Overview (Featured Props.) Widget issues

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#453]
- [ ]  **1. Property Overview Widget has an option to show Featured properties without any child properties, this option does not work:** 

Backend Widget Config: 
![image](https://cloud.githubusercontent.com/assets/19193013/26159868/6a259052-3b28-11e7-92df-474b68ff1612.png)

Frontend: 
![image](https://cloud.githubusercontent.com/assets/19193013/26160037/ca4268f2-3b28-11e7-959d-92bed293aec3.png)

**Comment by Mashenka** [comment]
@ElenaRad did you check on another theme?

**Comment by ElenaRad** [comment]
@Mashenka, yep, this issue is on other themes as well.

**Comment by alimuzzaman** [comment]
@ElenaRad 
This isn't an issue this is how it should be work. 
Disabling **Show Children** ensure that featured child property would not be listed on the overview as listing. 
We can put another option to disable this **Child Properties section**

**Comment by ElenaRad** [comment]
@Mashenka @alimuzzaman 
Maybe add two checkboxes or a dropdown, and add a description as it's confusing for the customer.

**Comment by Mashenka** [comment]
@alimuzzaman 
>We can put another option to disable this Child Properties section

sounds good

**Comment by alimuzzaman** [comment]
@ElenaRad @Mashenka Sorry that was a bug. I have fixed it.

**Comment by ElenaRad** [comment]
@Mashenka @alimuzzaman
FYI: my slack is down. Alim, do I need to do this on a fresh install?

**Comment by alimuzzaman** [comment]
@ElenaRad 
No, need for fresh install.

**Comment by ElenaRad** [comment]
@Mashenka @alimuzzaman
fyi: slack is down.    Alim, works now, but the styling is off, can you fix it? 

![image](https://cloud.githubusercontent.com/assets/19193013/26221375/e5d938c4-3c1e-11e7-8fa2-32b78a69fd0b.png)

**Comment by alimuzzaman** [comment]
@ElenaRad I am not good at fixing styles. If you can tell me exactly what should I do then I can fix.

**Comment by alimuzzaman** [comment]
@ElenaRad Maybe that needs to be fixed in theme.

**Comment by Mashenka** [comment]
@ElenaRad styles relate to a theme.  you can create an issue in Avalon theme for Den
