### ISSUE TITLE
Overview of Parent  summary is incorrect 

### ISSUE THREAD

**Issue by ElenaRad** [wp-property/wp-property#457]
Site: https://sandbox-uds-io-elena.c.rabbit.ci/  

- [x]   As per image, the parent property overview on should display the summary of all properties. At the moment this option does not work, displays price for one property only.

![image](https://cloud.githubusercontent.com/assets/19193013/26212849/a5a5f69e-3bff-11e7-91af-cc222e8dcf8d.png)

**Comment by alimuzzaman** [comment]
@ElenaRad is there any settings for this option?

**Comment by alimuzzaman** [comment]
@ElenaRad I have fixed the issue. You can review now.

**Comment by ElenaRad** [comment]
all set
