### ISSUE TITLE
Update code according to  metabox upgrade

### ISSUE THREAD

**Issue by alimuzzaman** [wp-property/wp-property#458]
Metabox plugin has been upgraded on wp-property. We need to upgrade our code according to it. Some function has been moved/renamed.
Note: inherited field needs to be checked.

**Comment by Mashenka** [comment]
I have assigned this task to you.

**Comment by alimuzzaman** [comment]
@Mashenka **Falls Under** should it be disabled? I have enabled in the last commit. I thought that was done by mistake.

**Comment by Mashenka** [comment]
don't know, can you clarify

**Comment by alimuzzaman** [comment]
![image](https://user-images.githubusercontent.com/6744156/27841522-1555e4d8-6124-11e7-84d6-526c3ebab3b5.png)

**Comment by Mashenka** [comment]
no, it shouldn't be disabled, please enable

there was an option to enable/disable here  
![image](https://user-images.githubusercontent.com/5111163/27841569-4df92a7a-610b-11e7-9861-849351a91967.png)

**Comment by alimuzzaman** [comment]
@Mashenka Check now, it should work as expected.
That was got hidden because of my mistake on settings v2. But the logic to hide **Falls Under** from property edit page seems missing for a year unless user creates attribute `parent`.

**Comment by Mashenka** [comment]
@alimuzzaman I can't merge now your commits, please check or do new pull request - https://github.com/wp-property/wp-property/pull/492
