### ISSUE TITLE
[QA 2.3] feature flags

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#469]
- [ ] **Legacy widgets.** (Featured Properties and Latest Properties) Should be disabled on new installs. But in fact, they are showing as enabled and do not exist in widgets tab. There was also option in Setting/Main tab to enable them "Enable Legacy Features".

- [x] **Freemius** We do not need that for now. Should be always disabled and need to hide from the settings tab at all.

- [x] **Settings Version 2** should be some explanation. This feature flag enables faster saving of developer tab's attributes.

- [x] **Settings Backups.** Need to be enabled on all installs after update.

- [x] **Standard  Location Taxonomy.** Should be enabled on new installs. 

- [x]  **Standard Property Type.** Should be enabled on new installs. 

- [x] **Meta Attributes Legacy Meta fields. In v2.2.1 meta fields have been merged with attributes. This includes default Phone Number.**  - Phone number still in Main tab on new installs. 
on old installs should be disabled.

- [x] **Enable Settings Search.** Should be enabled everywhere.

**Comment by alimuzzaman** [comment]
Not clear about legacy widgets.
Will **Settings Version 2** be enabled on old install?

**Comment by Mashenka** [comment]
yes. As I  understand that will make settings page work quicker? That shouldn't break anything. But I will test again.

**Comment by Mashenka** [comment]
Fatal error: Using $this when not in object context in Z:\home\latest.loc\www\wp-content\plugins\wp-property\lib\features\taxonomy-wpp-listing-type\taxonomy-wpp-listing-type.php on line 99
https://www.screencast.com/t/ihvtQ3wbGM7a

**Comment by Mashenka** [comment]
Legacy widgets still showing as enabled on new installs
