### ISSUE TITLE
[QA 2.3 ] google map's api key settings

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#471]
at the moment there is no server and browser API key. It seems there only one for both, 

need to check and corrected our options and docs in help tab
![image](https://cloud.githubusercontent.com/assets/5111163/23908036/807513ac-08db-11e7-9976-8f40fa96f1ec.png)

**Comment by Mashenka** [comment]
it seems you changed docs but UI still the same, or what was changed?

**Comment by alimuzzaman** [comment]
@Mashenka User should provide two key. Should I add Optional on the second field?

![settings develop alim wordpress](https://user-images.githubusercontent.com/6744156/28114052-f03a8480-6720-11e7-825c-eb73b0935622.png)

**Comment by Mashenka** [comment]
No, that's fine
