### ISSUE TITLE
Property Search not working if attribute value contain slash symbol

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#494]
test attribute

![image](https://user-images.githubusercontent.com/5111163/28088987-1f877982-6690-11e7-9550-a65d7c58315f.png)

properties
https://workspace.uds.io/wp-admin/post.php?post=784344&action=edit
https://workspace.uds.io/wp-admin/post.php?post=779066&action=edit

search
https://workspace.uds.io/search-2/

**Comment by fqjony** [comment]
@Mashenka fixed at `latest` and updated `wp-property` plugin on `https://workspace.uds.io`.
