### ISSUE TITLE
[QA 2.3] Feature flags

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#496]
O new install all feature flags should be disabled except:
 - Settings Backups.
- Legacy Attribute Input Types Enables legacy input types such as radio, WYSIWYG, etc.

On old installs after the update should be disabled all except:

- Legacy widgets. (Need also to check that this option enabling them)
- Settings Backups 
- Meta Attributes 
- Legacy Attribute Input Types Enables legacy input types such as radio, WYSIWYG, etc.

**Comment by fqjony** [comment]
@Mashenka done at https://github.com/wp-property/wp-property/commit/21eb9feced0cb0a38cdd661c9927573119318b99

**Comment by fqjony** [comment]
@Mashenka 
Checked `legacy widgets` feature flag - it is enabling them.
