### ISSUE TITLE
[QA 2.3] Overview widget duplicates attr

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#501]
https://udx-workspace-uds-io-production.c.rabbitci.com/properties/16332-weber-street-bennington-ne-68007/

![image](https://user-images.githubusercontent.com/5111163/28327166-5341650c-6beb-11e7-90e2-3471bd7fc3c6.png)

**Comment by alimuzzaman** [comment]
@Mashenka which price should I hide?

**Comment by Mashenka** [comment]
@alimuzzaman it seems that happens only in 2017, but remove all the same second and third

**Comment by Mashenka** [comment]
@alimuzzaman did you make some fix for that already, I do not see that issue any more

**Comment by alimuzzaman** [comment]
@Mashenka No, I didn't.  The problem is in **property-overview-v2**.

**Comment by Mashenka** [comment]
@SoSeductive can you suggest what to do?

**Comment by SoSeductive** [comment]
I know the problem. 
I did v2 widgets with new HTML structure.
I can do it. Here just need add some css styles.
