### ISSUE TITLE
[QA 2.3] property type showing as slug

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#502]
https://workspace.uds.io/properties/16332-weber-street-bennington-ne-68007/

![image](https://user-images.githubusercontent.com/5111163/28334534-156e5e10-6c04-11e7-9f0e-7bdb8cfce8c4.png)

**Comment by alimuzzaman** [comment]
@Mashenka How to replicate?

**Comment by Mashenka** [comment]
you can follow my link, theme 2017 - https://workspace.uds.io/properties/16332-weber-street-bennington-ne-68007/

widget property overview
