### ISSUE TITLE
move property type settings to term edit screen

### ISSUE THREAD

**Issue by ewsopp** [wp-property/wp-property#504]
Now that we are using a standard WordPress taxonomy to define listing types as terms, we can relocate the related settings to the term edit screen. Now all the related settings can be managed in the same area.

# WP-Property Property Type Settings

What we currently have in the WPP settings area.

![image](https://user-images.githubusercontent.com/5578537/29034331-035c86a4-7b66-11e7-9545-7cf71f90d9d7.png)

# WordPress Term Settings

Relocate the above settings to this area.

![image](https://user-images.githubusercontent.com/5578537/29034384-1f9694fe-7b66-11e7-8427-2edf6deb9e55.png)

**Comment by Mashenka** [comment]
@ewsopp now terms again separate plugin. That might cause conflicts. What do you think?

**Comment by ewsopp** [comment]
This has nothing to do with the Terms plugin.
