### ISSUE TITLE
2 or more checkbox attributes can't be used in property overview shortcode

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#507]
example

Attributes in Developer tab

![image](https://user-images.githubusercontent.com/5111163/38439028-e710e83a-39e4-11e8-94a7-e16cadab7940.png)

This one property with check=true
https://workspace.uds.io/wp-admin/post.php?post=153&action=edit
This one property with check2=true
https://workspace.uds.io/wp-admin/post.php?post=154&action=edit

This shortcode is working
[property_overview check=true]
This one not
[property_overview check=true check2=true]

**Comment by SoSeductive** [comment]
@Mashenka Links no more active

> This one property with checkbox=true
https://workspace.uds.io/wp-admin/post.php?post=153&action=edit
This one property with checkbox2=true
https://workspace.uds.io/wp-admin/post.php?post=154&action=edit

**Comment by Mashenka** [comment]
@SoSeductive yes, that is old task. But I have left examples of shortcodes which you could use to check that. Links set up again to be valid.

**Comment by Mashenka** [comment]
Can't replicate no more that issue
