### ISSUE TITLE
wp-property-terms warning

### ISSUE THREAD

**Issue by andypotanin** [wp-property/wp-property#510]
Reported by user:

> wp-property-terms gets the following error with PHP 7.1:  Warning: Parameter 2 to cf_taxonomy_post_type_binding::handle_taxonomy_archive() expected to be a reference, value given in /home/belcotest/public_html/wp-includes/class-wp-hook.php on line 298

**Comment by andypotanin** [comment]
Is `cf_taxonomy_post_type_binding::handle_taxonomy_archive` one of ours?

**Comment by antonkorotkov** [comment]
Looks like ours but goes from `vendor`

**Comment by pemaxim** [comment]
@andypotanin @antonkorotkov I think, the issue should be created in https://github.com/wp-property/wp-property-terms repository.

WP-Property Terms uses forked library https://github.com/usabilitydynamics/wp-tax-post-binding  Native library has not being supported 3 years.

I included the library to support custom post type for every term. So every term could have own single page with title, content, options... It was designed before term meta was added to WordPress. The custom term's post type for taxonomy can be enabled here: 

![image](https://user-images.githubusercontent.com/308489/30582992-5364564c-9d2e-11e7-99df-18ff29fb3044.png)

So, we should determine if we want to continue supporting the custom term post type feature or get rid of it. If we support - need to update library: https://github.com/UsabilityDynamics/wp-tax-post-binding/ and update vendor requirement with new version.

**Comment by andypotanin** [comment]
@pemaxim @antonkorotkov we want to be able to create landing pages for terms. If we can accomplish that with WP-Property Layouts and not deal with custom posts being created - great.

**Comment by ingen0s** [comment]
Is this resolved now?

**Comment by andypotanin** [comment]
@antonkorotkov Please let us know when you're back from vacation.

**Comment by antonkorotkov** [comment]
Does it still make sense? If so then I need allocate time for this.

**Comment by ingen0s** [comment]
@antonkorotkov I have tried but failed so far - I would be interested to see what your solution would look like - but I am sure you are a busy man.

**Comment by antonkorotkov** [comment]
I spent some time trying to fix this. Here is my fix https://github.com/UsabilityDynamics/wp-tax-post-binding/commit/124896f3094cfdfa2d1bb7e49a09bc6da1b202ab 

But in order to fix it in plugin we need to release new lib version and update plugin with it.

**Comment by antonkorotkov** [comment]
Library has been updated in WP-Property and WP-Property Term add-on. Fix will be available after next release of these.
