### ISSUE TITLE
property overview mobile view styles

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#511]
Currently looking like this 
![image](https://user-images.githubusercontent.com/5111163/29790007-c2537c58-8c40-11e7-85a5-78230163530e.png)

https://wordpress.org/support/topic/properties-not-displaying-correctly-in-mobile-view/#post-9442293

**Comment by SoSeductive** [comment]
@Mashenka Done
![workspace uds io-properties](https://user-images.githubusercontent.com/2156026/40614514-bf8046e2-628b-11e8-907f-aa6c223e61d0.png)
