### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by mulletmaniac** [wp-property/wp-property#513]
**Map not showing here:** 
http://riverwoodproperties.com/retail-centers/

**Embed code:**
[supermap map_width="600" property_type=all market_area=all availability=all sort_by="post_title" per_page=100 sort_order="ASC"]

**Diagnoses from the original website developer:**

> "The Javascript code for the maps is generated from within one of the property manager plugins.  However, the mechanism they are using is running it back thru WP's post process which is using the wpautop() function to insert paragraph tags around standalone carriage returns.  Since these are located within Javascript code blocks, the wpautop() function is screwing up the code syntax with embedded `<p>` tags.  Do a view source on the page and you'll see it. That's what needs to get turned off or worked around to get the script code to render cleanly."

Just need to know what to do to make this work.

Thanks in advance!

**Comment by Mashenka** [comment]
Hello @mulletmaniac 

How did you insert map there? Using text widget or just in content?

**Comment by mulletmaniac** [comment]
Just in the content.

**Comment by Mashenka** [comment]
can you check in text tab that there are no any extra tags like `<p>` - 

![image](https://user-images.githubusercontent.com/5111163/30110645-760b1836-9313-11e7-945c-5724dd8e4ff7.png)

**Comment by Mashenka** [comment]
also please check all these settings - https://www.usabilitydynamics.com/product/wp-property-supermap/docs/required-settings-for-wp-property-super-map

**Comment by mulletmaniac** [comment]
Maria,

Greatly appreciate your help. I went through each of the settings and recommendations one by one (including switching themes and de-activating plugins - at the same time). Unfortunately to no avail.

I believe it has to go back to the original developer's comments around wpauth(). Please see below.

> "the wpautop() function is screwing up the code syntax with embedded `<p>` tags. Do a view source on the page and you'll see it. That's what needs to get turned off or worked around to get the script code to render cleanly."

Any recommendations here? Thanks again for all your help. Greatly appreciated.

**Comment by alimuzzaman** [comment]
@mulletmaniac, 
Which version of the wp-property version are you using? 
I don't see any way that could happen because we removed all new line.
For now, try [this](https://customcreative.co.uk/resolving-wpautop-and-shortcodes/) while we are working on a fix.
The problem could be on the theme. Sometimes theme uses autop in code. What is the name of the theme? Try after changing the theme and let me know if it has the issue on other themes.

@Mashenka It would be helpful if I can get the theme for debugging.
I wasn't able to replicate the issue on local.

**Comment by alimuzzaman** [comment]
@mulletmaniac Which server you are using?

**Comment by Mashenka** [comment]
@mulletmaniac can you try to reinstall wp-property from WordPress. We see some not latest files on your site.
