### ISSUE TITLE
Agents. Add ability to add other agent attributes to the crm notifications.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#52]
At the moment we can use only [agent_email] in the crm notifications. - http://screencast.com/t/6A8yZYiWssM

**Comment by andypotanin** [comment]
Can you put together a list of which attributes we should add?

**Comment by Mashenka** [comment]
Such as
1) [agent_name]  - in agent's profile they as users also have [display_name] and [username]
2) [agent_phone_number] -  in agent's profile [phone_number]

**Comment by theamok** [comment]
I am pretty sure Max just did this while working on SMS. So it'll be v2.0
release, but remind him just in case.

Andy Potanin, CEO
Usability Dynamics, Inc.
http://UsabilityDynamics.com http://usabilitydynamics.com/
Direct: 910.742.0111 | Office: 800.270.0781
andy.potanin@usabilitydynamics.com

CONFIDENTIALITY NOTICE

This electronic mail message, including any and/or all attachments, is for
the sole use of the intended recipient(s), and may contain confidential
and/or privileged information, pertaining to business conducted under the
direction and supervision of Usability Dynamics, Inc. All electronic mail
messages, which may have been established as expressed views and/or
opinions (stated either within the electronic mail message or any of its
attachments), are left to the sole responsibility of that of the sender,
and are not necessarily attributed to the sending organization.
Unauthorized interception, review, use, disclosure or distribution of any
such information contained within this electronic mail message and/or its
attachment(s), is (are) strictly prohibited. If you are not the intended
recipient, please contact the sender by replying to this electronic mail
message and delete this message from your system, including any
attachments.
