### ISSUE TITLE
after wp-propety update new styles always enabled

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#537]
example 
https://workspace.uds.io/properties/commercial-retail-for-sale-384-yonge-st-499000-00/
they should be always disabled in any case, a new site or update on old site
and also not clear for first look that legacy widgets tag is responsible for new styles 

if there is an ability need to add styles word

**Comment by SoSeductive** [comment]
@Mashenka Done

**Comment by Mashenka** [comment]
Layouts always disabled
 Legacy widgets and styles always enabled
 Setup Assistant always disabled
 Settings Backups always disabled
 Settings Version 2 always enabled
 Disable Editor always disabled
 Listing Policies always disabled
 Schools Standard Taxonomy always disabled
 Listing Labels always disabled
 Standard Location Taxonomy always disabled
 Advanced Rewrite Rules always disabled
 Landing Page Categories always disabled
 Standard Property Type always disabled
 Standard Property Status always disabled
 Rooms always disabled
 Categorical Taxonomy always disabled
 Field Aliases always disabled
 Meta Attributes Legacy Meta fields. on old enabled, on new disabled
 Legacy Attribute Input Types always enabled
 Enable Settings Search always disabled(for now)
 Standard Attributes Matching and Terms always disabled
 Legacy Taxonomies always disabled
 RETSCI Client always disabled
