### ISSUE TITLE
Number of rows per page not working

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#538]
https://workspace.uds.io/wp-admin/edit.php?post_type=property&page=all_properties

![image](https://user-images.githubusercontent.com/5111163/35852524-cf945bae-0b33-11e8-9c97-e37a5815a4fc.png)

**Comment by SoSeductive** [comment]
Issue in WP-CRM, not in WP-Property
Here we can see function which works not correct and crashed wp-property plugin function
https://github.com/wp-crm/wp-crm/blob/v1.0/lib/class_functions.php#L2862
