### ISSUE TITLE
add feedback tab to latest branch

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#545]
this os from released version
![image](https://user-images.githubusercontent.com/5111163/38570046-87990234-3cf5-11e8-829f-f8640c69e74d.png)

here is Anton's commit to v2
https://github.com/wp-property/wp-property/commit/b90f81953c405e999ecc2babbec0d387d8e19ab6

**Comment by Mashenka** [comment]
checkboxs are not visible
![image](https://user-images.githubusercontent.com/5111163/38574312-36fc829a-3d01-11e8-8582-fae607a181c4.png)

**Comment by Mashenka** [comment]
https://github.com/wpCloud/wp-stateless/commit/fadcfd1502c5af44e65ced83b49c5a1135d8aa98

**Comment by SoSeductive** [comment]
@Mashenka Done

**Comment by SoSeductive** [comment]
Tried to fix issue in "feedback form" tab.
When we save settings - "Feedback" tab has opening and propose to add feedback.
I tried to add code like this - ["Link to commit"](https://github.com/wp-property/wp-property/pull/539/commits/89e4968df64a9bf98da4518cf8db478a40b5c6bf), but I see new problem. After save settings form HTML transferred into another place and looks not good.
![892658de43](https://user-images.githubusercontent.com/2156026/38808011-3c62714c-4187-11e8-8875-01e76d62ea36.png)
 I think this is hubspot form feature.

**Comment by alimuzzaman** [comment]
Something move .hbspt-form out from #hbspt_feedback_form.
We can simply move that again to original position (In ajax succes of onSaveSettingsResponse() function ).
Or try to find out what is causing the problem.

**Comment by Mashenka** [comment]
https://workspace.uds.io/wp-admin/edit.php?post_type=property&page=property_settings

only in Chrome

submit button not working
![image](https://user-images.githubusercontent.com/5111163/38891936-85ada60c-428e-11e8-84fa-a17070b43f64.png)

and also toggle not working
![image](https://user-images.githubusercontent.com/5111163/38891995-b13a2552-428e-11e8-8df9-653c30237d08.png)

and after I have submitted the form from another browser I see just blank page and settings page is forcing to go to feedback with no form

![image](https://user-images.githubusercontent.com/5111163/38892422-d5fe24b4-428f-11e8-9ae9-98a74283062c.png)

**Comment by SoSeductive** [comment]
@Mashenka Done.

**Comment by Mashenka** [comment]
Ok, so in conclusion we removed Feedback form for now
