### ISSUE TITLE
fix option to order images in Media tab

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#549]
that should effect [property_responsive_slideshow] and Property Gallery widget

![screen shot 2018-04-24 at 4 41 53 pm](https://user-images.githubusercontent.com/5111163/39190973-7401b52e-47de-11e8-9340-77a38bb0ae03.png)

Now after ordering images return to initial order

**Comment by SoSeductive** [comment]
@Mashenka Done

**Comment by Mashenka** [comment]
@SoSeductive not working for me - https://workspace.uds.io/properties/commercial-retail-for-lease-222-spadina-ave-825-00/

**Comment by Mashenka** [comment]
ok, working now

**Comment by Mashenka** [comment]
@SoSeductive Can you make sure that images remaining in the same order which they were set up in old media tab? After update they become in the order they were added to the site.
