### ISSUE TITLE
Property Media now displaying 

### ISSUE THREAD

**Issue by travisbevan** [wp-property/wp-property#554]
I have responsive image property_responsive_slideshow set up. But I am not getting a image gallery anywhere on any of the listing pages. 

I have tried default single and page, all the templates and nothing seems to work. 

I am running Madison which doesn't give any options. 

I have also tried putting the short code into the text, and also the get <?php echo do_shortcode('[property_slideshow]'); ?> with no success.. 

I have even gone into the theme files and tried to add it with out much success either.

**Comment by Mashenka** [comment]
Hello

did you put shortcode like that [property_responsive_slideshow] , did you see images on edit property page on the backend? Screenshots are welcome

**Comment by travisbevan** [comment]
The only way I was able to get the slide show working was to use WP-Property: Slideshow. But I had to add the images into that inside the property page. 

The media section under property details does not display images on the listing page at all.

**Comment by Mashenka** [comment]
you didn't answer my questions

disablу all third party plugins to investigate the issue

**Comment by travisbevan** [comment]
Once I activated the WP-Property: Slideshow and set it up. I did not need to add a short code. It just automatically added it in with Madison Theme. 

I am trying to get this plugin working with Ultra Theme by Themify which is a theme/framework builder. But the extremely vague customization of template files aren't helping to much. I copy the property.php file over but can not access it through Themify. And Themify has the option to build page playouts as templates, but WP-property does not know where to locate the page layouts created by Themify.

**Comment by alimuzzaman** [comment]
@tpebic Can you please clarify,
1. The automatic integration not working?
  Madison Theme doesn't support Responsive Slideshow. You have to do customization.
2. The short-code not working?

**Comment by travisbevan** [comment]
Yes I got the slideshow to work on Madison and ultra theme with a short code. 

But I am unable to set up a template page for listings to customize the look in Madison or Ultra themes. 
The property.php page is a spider web of PHP includes and styles settings.  The documentation does not really explain anything on how to customize the listing template.

This is the listing page style I would like to achieve.
![07-singel-property-page](https://user-images.githubusercontent.com/32349942/40017597-72d047d2-577f-11e8-895b-29fb4db88d7e.jpg)
Every time I try and change the style of the Attributes nothing really happens because of all the PHP/styles attached to 3 or 4 pages after property.php

**Comment by Smoot328** [comment]
@tpebic we'd be happy to help get this working to your satisfaction. We offer consulting services to provide support for customizing our products. This is an hourly paid services and will enable you to complete this task as soon as possible. let me know if your interested in our help.

**Comment by Mashenka** [comment]
Hello @tpebic

The new release of WP-Property should resolve an issue with attaching images to the single property.
