### ISSUE TITLE
Fatal error: Only variables can be passed by reference wp-property/static/views/admin/settings-developer-attributes.php on line 116

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#557]
![image](https://user-images.githubusercontent.com/5111163/40438140-f7a8f700-5ebf-11e8-9283-290f0617a18b.png)

**Comment by alimuzzaman** [comment]
`asp_tags` is enabled in php.ini that is conflicting with Underscore js template.
Disabling `asp_tags` will solve the issue.

http://php.net/manual/en/ini.core.php#ini.asp-tags

It's not commonly used and removed in PHP 7
