### ISSUE TITLE
Admin CSS conflicts with Comet Cache accordions

### ISSUE THREAD

**Issue by garretthyder** [wp-property/wp-property#560]
**Describe the bug**
There's some .clearfix CSS added within wpp.admin.css which conflicts with Comet Cache settings accordions and I wouldn't be surprised if other plugins have issue with it as well. The CSS of issue is here;
```
.clearfix:after {
  content: ".";
  display: block;
  clear: both;
  visibility: hidden;
  line-height: 0;
  height: 0;
}
.clearfix {
  display: inline-block;
}
html[xmlns] .clearfix {
  display: block;
}
* html .clearfix {
  height: 1%;
}
```
In the case of Comet Cache this breaks their setting accordions making them uncollapsible as they have .clearfix class which WPP is forcing to a display:block.
![screen shot 2018-06-07 at 9 47 49 am](https://user-images.githubusercontent.com/8726005/41113975-eb121246-6a37-11e8-8c2d-58fcdf1fea79.png)

Please update wpp.admin.css to namespace this CSS for .clearfix class so as to only affect the WPP settings pages or the specific elements they were added for.

**To Reproduce**
1. Install Comet Cache (I have Pro but should also affect free) - https://en-ca.wordpress.org/plugins/comet-cache/
2. Navigate to the Comet Cache settings
3. Attempt to close the accordions.
4. Inspect to note the display block from wpp.admin.css on .clearfix is blocking the collapse.

**Expected behavior**
I expected the accordions to work as normal without the conflict.

**Screenshots**
![screen shot 2018-06-07 at 9 47 49 am](https://user-images.githubusercontent.com/8726005/41113975-eb121246-6a37-11e8-8c2d-58fcdf1fea79.png)

**Desktop (please complete the following information):**
 - OS: OS X 10.10.5
 - Browser: Chrome
 - Version: WPP 2.3.3

**Additional context**
This is a Plugin Conflict where WPP is adversely affecting other plugins.

**Comment by SoSeductive** [comment]
Issue fixed and added into `latest` branch

**Comment by garretthyder** [comment]
Thanks @SoSeductive
