### ISSUE TITLE
Issue with edit child property

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#566]
Right now issue can't be replicated on workspace, we are waiting for details from client

https://wordpress.org/support/topic/property-data-does-not-save-and-php-warning/

>The issue with Property info not saving only seems to occur when we select a ‘Falls Under’ building to make our property a child property. Cannot edit a current child property or add a new child property without data not saving.

[14-Jul-2018 20:24:42 UTC] PHP Warning: Declaration of RWMB_Wpp_Inherited_Field::show($field, $saved) should be compatible with RWMB_Field::show($field, $saved, $post_id = 0) in /public_html/wp/wp-content/plugins/wp-property/lib/classes/fields/class-wpp-inherited.php on line 13
[14-Jul-2018 20:24:42 UTC] **PHP Fatal error:** Uncaught Error: Call to undefined method RWMB_Wpp_Inherited_Address_Field::datalist_html() in /public_html/wp/wp-content/plugins/wp-property/lib/classes/fields/class-wpp-inherited-address.php:39
Stack trace:
#0 /public_html/wp/wp-content/plugins/wp-property/lib/features/meta-box/meta-box/inc/field.php(612): RWMB_Wpp_Inherited_Address_Field::html(Array, Array)
#1 /public_html/wp/wp-content/plugins/wp-property/lib/features/meta-box/meta-box/inc/field.php(67): RWMB_Field::call(Array, ‘html’, Array)
#2 /public_html/wp/wp-content/plugins/wp-property/lib/features/meta-box/meta-box/inc/field.php(612): RWMB_Field::show(Array, true, 3633)
#3 /public_html/wp/wp-content/plugins/wp-property/lib/features/meta-box/meta-box/inc/meta-box.php(235): RWMB_Field::call(‘show’, Array, true, 3633)
#4 /public_html/wp/wp-admin/includes/template.php(1063): RW_Meta_Box->show(Object(WP_Post), Array)
#5 /home/daylig07/public_html/wp/wp-admin/edit-form-adv in /public_html/wp/wp-content/plugins/wp-property/lib/classes/fields/class-wpp-inherited-address.php on line 39
[14-Jul-2018 20:24:42 UTC] PHP Warning: Declaration of RWMB_Wpp_Inherited_Field::show($field, $saved) should be compatible with RWMB_Field::show($field, $saved, $post_id = 0) in /public_html/wp/wp-content/plugins/wp-property/lib/classes/fields/class-wpp-inherited.php on line 13

**Comment by ottomek** [comment]
Hi,
Here is the wp-property configuration for this issue. We do have the wp property meta box files installed and active. 
[daylightproperties-wp-property.2018-07-18.json.zip](https://github.com/wp-property/wp-property/files/2206579/daylightproperties-wp-property.2018-07-18.json.zip)

I'm testing a few other items and checking on plugin conflicts now. 

Thanks,
John

**Comment by ottomek** [comment]
Hi,
I've tried these items but still having the issue.
- switched to WP twentyseventeen theme
- disabled 3rd party plugins
- deleted wp property plugin files and uploaded fresh install via ftp
- tried several versions of php in cpanel
- created and installed a new google maps js and geolocation api

Question: Will wp-property add-ons work in a cloned wp site (on same url) if these are not activated? I've duplicated the site in another folder to troubleshoot but I cannot add the add the activation keys since they are used on the live site.

John

**Comment by Mashenka** [comment]
@ottomek add-ons license only influences on updates, they are no how influence on plugin's functionality.

 The Site ID & Public Key are  only for developers and not required options.

We are checking your configuration and will come back to you as soon as possible.

**Comment by Mashenka** [comment]
@ottomek I have uploaded your configuration, what type in your case is parent property and what is child?

**Comment by ottomek** [comment]
@Mashenka 
Parent Property/Buildings are Commercial Building, Residential Building, Commercial and Residential 
Examples: Bellingham Hardware Building, Herald Building, Bellingham Hardware Building.

Child Property are anything else; Retail, Nightclub, Small Office, Office, Loft, Studio, 1 Bedroom...

**Comment by Mashenka** [comment]
@ottomek I have replicated an issue. 

@SoSeductive you could check example here - https://workspace.uds.io/wp-admin/post.php?post=422&action=edit

I have set up nightclub property type for child property and commercial building for parent property

**Comment by Mashenka** [comment]
@SoSeductive I can confirm, that issue was fixed on workspace

@ottomek you could check by yourself from this branch - https://github.com/wp-property/wp-property/tree/metabox-hotfix
Will wait for your feedback.

**Comment by SoSeductive** [comment]
@Mashenka After positive feedback we can do a merge into latest branch #567

**Comment by ottomek** [comment]
@SoSeductive Yes this fix is working on my test site and the live production site. Thanks for the fix.
