### ISSUE TITLE
Default image for property type not showing in Developer tab

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#568]
... but working/showing on particular property type as expected.

![image](https://user-images.githubusercontent.com/5111163/43131936-f2cca728-8f42-11e8-8b8d-f8468b78df2b.png)

**Comment by SoSeductive** [comment]
@Mashenka Done. 
Link for testing https://udx-ci-develop-den.rabbit.ci/wp-admin/edit.php?post_type=property&page=property_settings#tab_admin_tools
