### ISSUE TITLE
values for taxonomies not showing if not using native metabox

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#569]
but using withing attributes

https://workspace.uds.io/wp-admin/post.php?post=430&action=edit

![image](https://user-images.githubusercontent.com/5111163/43210122-f3e64d4a-9036-11e8-85f8-358110842ae5.png)

![image](https://user-images.githubusercontent.com/5111163/43210180-1149cb3c-9037-11e8-8344-9407e5b9c27c.png)

**Comment by SoSeductive** [comment]
@Mashenka Fixed!
Issue was in `"WP Property Tems"` plugin, because in new version `metabox`, which we updated in `"WP-Property"`, field name returned in array, but in old version of `metabox` as string. I am already fixed it on `workspace` and pushed into `"Terms" repo` in hotfix branch.

**Comment by SoSeductive** [comment]
@Mashenka https://github.com/wp-property/wp-property-terms/pull/35

**Comment by pemaxim** [comment]
> Issue was in "WP Property Tems" plugin, because in new version metabox, which we updated in "WP-Property", field name returned in array, but in old version of metabox as string. I am already fixed it on workspace and pushed into "Terms" repo in hotfix branch.

@SoSeductive Did you add compatibility with old `metabox` version as well?

@Mashenka Was it tested? I do not see any updates here. Is it working with old and new metabox versions? Right?

**Comment by SoSeductive** [comment]
@pemaxim Yes. I checked this issue with old and new `metabox` versions and issue is resolved. Also @Mashenka told me what she tested and confirm that issue is resolved
