### ISSUE TITLE
Pagination when sorting is showing duplicate results

### ISSUE THREAD

**Issue by samjameswatson** [wp-property/wp-property#570]
**Describe the bug**
Pagination when sorting is showing duplicate results and missing properties out between pages. This only happens if the properties are sorted and have the same value going over the end of a page.

**To Reproduce**
This is WP 4.9.7 and WPP 2.3.5 on twentyseventeen theme. All options set to defaults except "price" attribute has been set as sortable (both currency and number data entry types have this issue). Shortcode is [property_overview sort_by=price sort_order=ASC]

Issues happens with standard pagination and load more pagination. We have added 12 properties with exactly the same details (and prices) but with an ID so that we can see which ones are showing.

1. Go to http://wpp-pagination.dev2.lyles-sutherland.co.uk/
2. Look at numbers of each property and see that they are duplicating and some properties are missed

**Expected behavior**
I'd expect all the properties to show. Ideally we would be able to provide an option for "secondary" sorting i.e. sort by price but then within that sorting sort by title or bedrooms etc.

**Comment by Mashenka** [comment]
@Samsonator thank you for pointing. We are going to check that. Do you have the same behavior with other pagination types?

**Comment by samjameswatson** [comment]
Hi @Mashenka, yes we can see it with slider and load more and numeric.

**Comment by samjameswatson** [comment]
We can give admin access to the development site if that is helpful

**Comment by Mashenka** [comment]
Thanks. I'm going to check on our test sites

**Comment by Mashenka** [comment]
@Samsonator We have replicated the issue. Thank you for pointing. We will try to put that fix to the next release

@SoSeductive you could replicate here - https://workspace.uds.io/properties

**Comment by samjameswatson** [comment]
@Mashenka That's great thanks for letting me know. Do you know if the ability to have a secondary "sort" is planned 
i.e. after sorting by bedroom -> if two properties have 3 bedrooms -> "how do they sort within those that have 3 bedrooms".

**Comment by Mashenka** [comment]
@Samsonator no, that is not possible at all right now

**Comment by samjameswatson** [comment]
Ok thanks for letting me know

**Comment by samjameswatson** [comment]
Any update on this issue?

**Comment by Mashenka** [comment]
@Samsonator Thank you for the update. This issue should be started this week.

**Comment by Mashenka** [comment]
@Samsonator We are started on a fix of the current issue and now not able to replicate. Can you mention which properties are duplicating. Which has the same value for some particular attributes, which you set up for sotring?

**Comment by samjameswatson** [comment]
Hi @Mashenka , sorry I've since taken the website from my initial comment offline.

As described all I was doing was having properties sorted by price but then having multiple properties with the same price. If you have enough to fill one page and continue onto the next i.e. if you have 5 properties per page:

Page one
-->
Property1 - £500
Property2 - £500
Property3 - £500
Property4 - £500
Property5 - £500
--> Next Page
Property4 - £500 (This is where certain properties are omitted)
Property3 - £500 (This is where certain properties are omitted)

Do you want me to set up another site showing this happening?

**Comment by Mashenka** [comment]
@SoSeductive try again https://workspace.uds.io/properties/ it seems I have repeated. property # 1 is replicating in the end

**Comment by Mashenka** [comment]
@Samsonator no, thanks. it seems I was able to replicate ^ you could also check on that site is that what you mean

**Comment by SoSeductive** [comment]
@Samsonator I have added fixes. Can you test it in this branch https://github.com/wp-property/wp-property/tree/develop-den ?

**Comment by Mashenka** [comment]
Issue has been resolved

**Comment by samjameswatson** [comment]
@Mashenka Sorry, only just had the chance to test this. I can confirm that properties are now displaying "across" pages even if they have the same value for the sorted attribute. However, it looks like the properties are not sorting properly. When I set them to sort by Price ASC or DESC and had 10 properties costing £750 and 2 properties costing £450 and £350 respectively, the properties didn't sort correctly. @SoSeductive

**Comment by Mashenka** [comment]
@Samsonator what particular is not correct in your sorting, can't replicate here - https://udx-ci-develop-den.rabbit.ci/properties/

**Comment by samjameswatson** [comment]
@Mashenka I can see the 150 and 200 price properties at the top but then if you click sort by Price it doesnt resort the price. I've changed the argument in the URL from ASC to DESC and I can't see the properties change order.

**Comment by Mashenka** [comment]
@Samsonator ok, see that. Сreated another issue for that - https://github.com/wp-property/wp-property/issues/586
