### ISSUE TITLE
Support tab issues

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#574]
- [x] on saving settings, forcing the page to the Support tab but all the same save settings, also messed up Support tab
![image](https://user-images.githubusercontent.com/5111163/45306432-550af900-b525-11e8-9c63-f068ea7f714f.png)

**Comment by Mashenka** [comment]
Also checkbox is not showing

![image](https://user-images.githubusercontent.com/5111163/45481988-8c5fec80-b755-11e8-8836-a5a04a0a8f2b.png)

**Comment by SoSeductive** [comment]
@Mashenka Done
Link for testing https://udx-ci-develop-den.rabbit.ci/wp-admin/edit.php?post_type=property&page=property_settings#tab_admin_tools
