### ISSUE TITLE
Add ! empty checks around foreach loops of $wp_properties['taxonomies'] to avoid errors

### ISSUE THREAD

**Issue by garretthyder** [wp-property/wp-property#578]
**Describe the bug**
In our install we've filtered out the feature taxonomies for property_feature and community_feature which on non-legacy installs wouldn't be setup anyway. When the taxonomies array is empty we start to get error messages as there's not checks for if empty prior to using the $wp_properties['taxonomies'] array.

**To Reproduce**
1. Enable Debug
2. Add the following filter to your theme;
```
// Suppress 'Features' and 'Community Features' taxonomies.
function wpp_remove_features_taxonomies( $taxonomies ) {
    unset( $taxonomies['property_feature'] );
    unset( $taxonomies['community_feature'] );
    return $taxonomies;
}
add_filter( 'wpp_taxonomies', 'wpp_remove_features_taxonomies' );
```
3. Reload the Admin list of properties as well as the front end.
4. See errors in debug.log

**Expected behavior**
Shouldn't receive errors instead should just catch the empty array and avoid the foreach loops.

**Error**
[17-Sep-2018 17:48:11 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/duttons/public_html/wp-content/plugins/wp-property/lib/shortcodes/property-attributes.php on line 22
[17-Sep-2018 17:48:11 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/duttons/public_html/wp-content/plugins/wp-property/lib/classes/class-admin.php on line 179

**Code to Fix**
*I did a mass search in the plugin to get a list of all instances where a foreach is done on the taxonomies array without first checking if it's empty.
- wp-property/lib/shortcodes/property-attributes.php on line 22
- wp-property/lib/classes/class-admin.php on line 179
- wp-property/lib/classes/class-admin.php on line 326
- wp-property/lib/template-functions.php on line 591
- wp-property/lib/class_functions.php on line 732 & 738

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version: 2.3.6

**Additional context**
It appears if you set WP_PROPERTY_FLAG_ENABLE_LEGACY_TAXONOMIES to false you should also end up with an empty taxonomies array which would cause these errors.

**Comment by Mashenka** [comment]
@garrett-eclipse thank you for the feedback. We will check that.

**Comment by Mashenka** [comment]
@garrett-eclipse We need some clarification from your side.

Which version of property are you talking about? Did you enable/disable feature flags?
Did you found that issue on the update?

And can you clarify what are you trying to do in general. Do you want to delete legacy taxonomies?

**Comment by garretthyder** [comment]
Hi @Mashenka, no worries

Which version of property are you talking about?
I'm using 2.3.6 of WP-Property

Did you enable/disable feature flags?
Yes see screen below;
![screen shot 2018-09-18 at 9 20 06 am](https://user-images.githubusercontent.com/8726005/45701483-23e18880-bb24-11e8-905d-dee54945ec66.png)

Did you found that issue on the update?
Yes, but that's unrelated I only found during update as I run through the backend after updates.

And can you clarify what are you trying to do in general. Do you want to delete legacy taxonomies?
Yes, I didn't need the Features or Community Features taxonomies so I suppressed them with the following code;
```
// Suppress 'Features' and 'Community Features' taxonomies.
function wpp_remove_features_taxonomies( $taxonomies ) {
    unset( $taxonomies['property_feature'] );
    unset( $taxonomies['community_feature'] );
    return $taxonomies;
}
add_filter( 'wpp_taxonomies', 'wpp_remove_features_taxonomies' );
```

The suppression works successfully so no issues there, just because the $taxonomies array is empty a bunch of errors pop into the logs as the WP-Property code often uses $taxonomies within foreach loops without checking if they're empty first. By first checking if things are empty you'll avoid flooding logs with the warnings.

Hope that clarifies
Cheers

**Comment by SoSeductive** [comment]
@garrett-eclipse I have added checks.  Can you test it in this branch https://github.com/wp-property/wp-property/tree/develop-den

**Comment by garretthyder** [comment]
Thanks @SoSeductive tested it out and it seems to remove the warnings specific to this issue.

Not sure if this should be handled here or another ticket but am now getting these warnings;
```
[20-Sep-2018 18:29:58 UTC] PHP Notice:  Undefined index: wpp-jquery-fancybox in /home/dev/public_html/duttons/wp-content/plugins/wp-property/lib/class_functions.php on line 1416
[20-Sep-2018 18:29:58 UTC] PHP Notice:  Trying to get property of non-object in /home/dev/public_html/duttons/wp-content/plugins/wp-property/lib/class_functions.php on line 1416
```

Also doing a code review you removed a bunch of spacing and it made me wonder if wp-property is following WP Coding Standards specifically Space Usage;
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage

**Comment by Mashenka** [comment]
@garrett-eclipse yes, that may be another issue next time.

@SoSeductive check those notices when you have time^

**Comment by SoSeductive** [comment]
@garrett-eclipse I can't repeat issue and don't see this notices

**Comment by garretthyder** [comment]
No worries @SoSeductive thanks for the update. If I come across the warning with better understanding will open a new ticket. Initial look at it seems the force_script_inclusion doesn't check that the $handle is even a key in $wp_scripts->registered which results in the two warnings. But I don't have a exact reproduction case for you at the moment.
