### ISSUE TITLE
Issue in wp property addon supermap plugin

### ISSUE THREAD

**Issue by tkalpit** [wp-property/wp-property#579]
wp property addon supermap plugin does not take my google map api key.

**Comment by Mashenka** [comment]
Hello.

Can you explain in more details? How do you know that wp property addon supermap plugin does not take your google map api key.

Check also your permalinks options.

Regards.

**Comment by tkalpit** [comment]
@Mashenka  In properties>settings>main tab set google api keys , same keys in browser and server column then when i reload page on front it shows 'for developers only' screen on map and in console it gives no api keys warning.

**Comment by Mashenka** [comment]
did you update your permalinks?

also, check  in your Google account that you have added Maps JavaScript API – 
![image](https://user-images.githubusercontent.com/5111163/45943901-e59b0c00-bff0-11e8-90c7-37b0b8115793.png)

**Comment by tkalpit** [comment]
@Mashenka 
I have done both your points but still i get no api keys in console and same thing 'for developer only'

**Comment by Mashenka** [comment]
try to recreate API key and put the new one.

**Comment by tkalpit** [comment]
I was recreate my api 4-5 times but nothing changed

**Comment by Mashenka** [comment]
Try also disable all third party plugins and change theme just to investigate the issue.

That is something we can't replicate. That could be investigated directly on your site on a paid basis. Use the Support tab in Wp-property plugin for paid support.

**Comment by oceandigital** [comment]
Tkalpit, I had the same issue a few weeks ago.  

Go to dashboard/settings/permalinks. Click Save. Click Save again. Clear your browser cache. I hope that works for you. Also in google api, don’t restrict to a domain name or IP.
