### ISSUE TITLE
WPML update, wp-property strings disappeared 

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#584]
Disappeared wp-property strings from this list, when string translation enabled
![image](https://user-images.githubusercontent.com/5111163/46016014-5b2fd680-c0dc-11e8-9b5a-59a1064b9723.png)

that was like in the screenshot
![image](https://user-images.githubusercontent.com/5111163/46247424-ecbc8280-c413-11e8-9e1f-b06db741c717.png)

**Comment by SoSeductive** [comment]
@Mashenka Issue not repeated, All works great. All what need - it is update settings in wpp plugin, On save settings we have action 'wpml_register_string' which show us strings of attributes values.
