### ISSUE TITLE
ASC and DESC sorting in Overview not working

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#586]
https://udx-ci-develop-den.rabbit.ci/properties/

with ASC and DESC parameters showing the same

![image](https://user-images.githubusercontent.com/5111163/46478399-94132e00-c7f5-11e8-9287-a78808ae1aff.png)

![image](https://user-images.githubusercontent.com/5111163/46478415-99707880-c7f5-11e8-94cc-6c459cec645d.png)

**Comment by SoSeductive** [comment]
@Mashenka Done

**Comment by Mashenka** [comment]
@SoSeductive working from the second attempt. From the first click, it remains the same

**Comment by SoSeductive** [comment]
@Mashenka 
If we use `[property_overview sort_by=price per_page=2 sort_order=DESC]` shortcode, on first click we have this request, with `sort_order=DESC`
`https://udx-ci-develop-den.rabbit.ci/properties/#/requested_page=1&sort_order=DESC&sort_by=price&i=1&unique_hash=41990`

on second click sort order change DESC to ASC

**Comment by Mashenka** [comment]
but I deleted parameters and now there just [property_overview]

**Comment by Mashenka** [comment]
ok. than issue fixed
