### ISSUE TITLE
Error on Default Property Page

### ISSUE THREAD

**Issue by oceandigital** [wp-property/wp-property#587]
**Describe the bug**
This:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (swiper.jquery.min.js.map, line 0)
/wp-content/plugins/wp-property/static/scripts/maps/swiper.jquery.min.js.map

**To Reproduce**
1. Go to Default Property Page
2. Use these shortcodes: [property_search per_page=12] [property_overview per_page=24]
3. See error on front-end

**Desktop (please complete the following information):**
 - OS: MacOS
 - Safari
 - Latest Version

**Comment by Mashenka** [comment]
Hello.

Wasn't able to replicate the issue here
https://udx-ci-develop-maria.rabbit.ci/properties/.

 Probably you could give more details.

Thanks

**Comment by oceandigital** [comment]
Server info
<img width="533" alt="screen shot 2018-10-06 at 1 00 25 pm" src="https://user-images.githubusercontent.com/36800889/46573773-f68c3b80-c967-11e8-87e7-2e74abf61f30.png">

Browser info
<img width="245" alt="screen shot 2018-10-06 at 12 58 54 pm" src="https://user-images.githubusercontent.com/36800889/46573774-f68c3b80-c967-11e8-8e6c-64c17d998e9b.png">

Default theme
<img width="347" alt="screen shot 2018-10-06 at 12 54 54 pm" src="https://user-images.githubusercontent.com/36800889/46573733-71a12200-c967-11e8-9c3a-d04ab0ab54cc.png">

All plugins deactivated
<img width="559" alt="screen shot 2018-10-06 at 12 55 23 pm" src="https://user-images.githubusercontent.com/36800889/46573734-71a12200-c967-11e8-882a-8829aadc545b.png">

WPP settings
<img width="743" alt="screen shot 2018-10-06 at 12 55 59 pm" src="https://user-images.githubusercontent.com/36800889/46573735-71a12200-c967-11e8-8d42-d369fdfde8b1.png">

I named my Properties page "Search"
<img width="332" alt="screen shot 2018-10-06 at 12 56 40 pm" src="https://user-images.githubusercontent.com/36800889/46573736-71a12200-c967-11e8-94ad-3430df5e023b.png">


Error happens on Search(Properties) page
<img width="410" alt="screen shot 2018-10-06 at 12 54 16 pm" src="https://user-images.githubusercontent.com/36800889/46573732-71088b80-c967-11e8-9167-791cd2ec676c.png">

**Comment by Mashenka** [comment]
Ok, I have replicated that issue only in Safari. Does that prevent you to do something?

**Comment by Mashenka** [comment]
@oceandigital ^

**Comment by SoSeductive** [comment]
@Mashenka Done. You can test it here https://udx-ci-develop-den.rabbit.ci/properties/

**Comment by oceandigital** [comment]
> Ok, I have replicated that issue only in Safari. Does that prevent you to do something?

Im not sure, there are some things not working properly but I dont know if this is the source. Im just trying to help kill one bug at a time so everything is working properly.

**Comment by Mashenka** [comment]
@SoSeductive still see

![image](https://user-images.githubusercontent.com/5111163/46623927-ed51c900-cb37-11e8-83ca-9e33a1a13898.png)

**Comment by SoSeductive** [comment]
@oceandigital This errors from `.map` file, which uses in `JS` or in `CSS` files. This is legacy technology which used all browsers, but only `Safary` still using it. This don't crash out plugin and will not affect on site or plugin work. In future we will clean `JS` and `CSS` libs from this including of `.map` files.
