### ISSUE TITLE
WPML.  issue with updating property

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#594]
Can't update the property
https://udx-ci-develop-maria.rabbit.ci/wp-admin/post.php?post=72&action=edit&lang=ru

revalidate option showing that all addresses is empty

![image](https://user-images.githubusercontent.com/5111163/48188107-93fed480-e345-11e8-8a86-7764250ada59.png)

however, 2 our those 6 showing on the map - https://udx-ci-develop-maria.rabbit.ci/supermap/

forum topic - https://wordpress.org/support/topic/supermap-on-translated-page-with-wpml/#post-10859335

**Comment by alimuzzaman** [comment]
> revalidate option showing that all addresses is empty

The problem was `WP_HTTP_BLOCK_EXTERNAL` was blocking our request to **maps.googleapis.com**.

**Comment by Mashenka** [comment]
ok, now working for me
