### ISSUE TITLE
Property type not translate in search form

### ISSUE THREAD

**Issue by rafso** [wp-property/wp-property#603]
In default search form, the property type label it is not translated.

how can i translate this? in which file?

![image](https://user-images.githubusercontent.com/1217957/68356433-1b199080-00f1-11ea-8c1d-d6422009c813.png)

**Comment by rafoelhonrado** [comment]
Hi rafso,
 You should translate the wpp-(language-code) file, in your case should be wpp-pt_BR (portuguese - BRAZIL)
This is the text to translate
![imagen](https://user-images.githubusercontent.com/31689/81190667-c2329400-8f7d-11ea-854c-606f532c3536.png)
This is the result
![imagen](https://user-images.githubusercontent.com/31689/81190725-d2e30a00-8f7d-11ea-9b28-e10a56e7d9e6.png)
