### ISSUE TITLE
Various functions in XML_Util being called as static but functions aren't marked static

### ISSUE THREAD

**Issue by markheydon** [wp-property/wp-property#611]
Probably not a massive issue on production use but when trying to develop/debug various errors such as the following occur.

> Deprecated: Non-static method XML_Util::createTagFromArray() should not be called statically

Depreciated in PHP 7 I think - but can't find the official notice right now.

Functions in XML_Util are already decorated as @static.

**Comment by SoSeductive** [comment]
@markheydon We updated lib Serialize\Unserialize. If you still have this issue and still need to fix it, you can download `develop` version of plugin and test it for now. We will do relize into `production` ASAP.

**Comment by planv** [comment]
This has been fixed in the latest release - https://github.com/wp-property/wp-property/releases/tag/2.4.2
Closing the ticket.

**Comment by markheydon** [comment]
Actually @planv @SoSeductive I don't think this is fixed after all. Did some major clean-up on server this weekend and now getting error again and from looking the referenced commit there is nothing changed in the code around static/non-static calls. The XML library you are using hasn't been updated since around PHP 5 by the looks so no surprise it's not working really!!!!!
