### ISSUE TITLE
Compatibility issue with WordPress 5.5

### ISSUE THREAD

**Issue by alimuzzaman** [wp-property/wp-property#613]
- [x] https://wordpress.org/support/topic/is-wp-property-being-supported-anymore/

- [x] https://wordpress.org/support/topic/sort-by-stopped-working-javascript-errors-on-page/

- [ ] https://wordpress.org/support/topic/updating-old-version-breaks-tags/

VariousJavaScript related issues.

**Comment by alimuzzaman** [comment]
Solved the first two issues.
Third issue: The problem doesn't seem to exist.

**Comment by liapotanin** [comment]
@alimuzzaman There was a request about the second issue in the contact form, but you already fix it.

**Comment by Becca800** [comment]
Still not solved. WP-property doesn't work with WP 5.5. No new release of WP-Property has been made. I don't see this "fix" anywhere. With 5.5 there are JS errors, pagination doesn't work, and neither does sorting. We have to roll back to the earlier version of WP.

**Comment by alimuzzaman** [comment]
@Becca800 the fix hasn't been published yet.


You can get fix for first two issues from here https://github.com/wp-property/wp-property/archive/cbd16cc83ac00891b3a17149796d6ce1488fd0f5.zip (Updated)

Let us know if this fix solves your problem.

**Comment by planv** [comment]
> https://wordpress.org/support/topic/is-wp-property-being-supported-anymore/

I have an error on this page, and I can't submit form. 

![изображение](https://user-images.githubusercontent.com/5268508/91313633-44a9c280-e7be-11ea-9664-f0d3084851c5.png)

![изображение](https://user-images.githubusercontent.com/5268508/91313882-96524d00-e7be-11ea-91ae-af20a3c6e292.png)

Also button `Add row` not working.

![изображение](https://user-images.githubusercontent.com/5268508/91314205-fa751100-e7be-11ea-8fb1-d0001a411125.png)


----------------------------
> https://wordpress.org/support/topic/sort-by-stopped-working-javascript-errors-on-page/

Confirm, it works.

**Comment by alimuzzaman** [comment]
@planv can you test again?

**Comment by planv** [comment]
@alimuzzaman Now I'm have an error 502.

<img width="1319" alt="изображение" src="https://user-images.githubusercontent.com/5268508/91411380-e974e000-e850-11ea-97d0-13b9272252f3.png">

I have updated `WPP` on `stateless.ci` from your branch.
You can test that on https://stateless.ci/wp-admin/admin.php?page=all_properties

**Comment by planv** [comment]
@alimuzzaman 

>  https://wordpress.org/support/topic/is-wp-property-being-supported-anymore/

Adding new rows on settings page works.

**Comment by planv** [comment]
@alimuzzaman 

I have JS error on `Facebook Tabs` add-on. Can you fix it?

<img width="1674" alt="изображение" src="https://user-images.githubusercontent.com/5268508/91895848-8f38ac80-eca0-11ea-949d-249792b01b88.png">

**Comment by alimuzzaman** [comment]
@planv please review again.

**Comment by planv** [comment]
@alimuzzaman I don't see your commit.

**Comment by planv** [comment]
@alimuzzaman It works, thanks.
