### ISSUE TITLE
Deleted items are no longer being removed on import

### ISSUE THREAD

**Issue by Becca800** [wp-property/wp-property#618]
Latest version of WP
Latest version of WP-property

I just realized while trying to figure out why the cron job is not working, that old properties are no longer being removed.
The schedules are either not being save to or pulled from the correct place.

I noticed that line 53 in cron.php (in the importer addon) should probably be changed to:

`$wp_load_path = preg_replace( '%wp-content[/\\\\]plugins[/\\\\]wp-property[/\\\\]addons[/\\\\]wp-property-importer[/\\\\]cron.php%ix', 'wp-load.php', __FILE__ ); `

But I don't think this fixes the cron not running and the old properties not being deleted.

**Comment by Becca800** [comment]
This DID fix the cron! My cron jobs are running again!

**Comment by Becca800** [comment]
Properties are being deleted now. So that code change above fixes the cron job and things are hunky dory. Hope it gets added to a release soon.

**Comment by planv** [comment]
Fixed in new release - https://github.com/wp-property/wp-property/releases/tag/2.4.2
Closing the ticket.
