### ISSUE TITLE
 XMLI. In some cases do not save more than 20 in other cases 49 attributes in schedule.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#62]
increase the max_input_vars setting from 1000 to 10000. However, the problem remains

Topics:

https://usabilitydynamics.com/products/wp-property/forum/topic/importer-losing-attributes/

https://usabilitydynamics.com/products/wp-property/forum/topic/attributes-get-lost-over-time-by-import-schedules/

https://usabilitydynamics.com/products/wp-property/forum/topic/xml-importer-saved-import-schedule-dropping-attributes/

https://usabilitydynamics.com/products/wp-property/forum/topic/after-saving-all-settingstabs-gone-me-too-1/?#post-23164

**Comment by pemaxim** [comment]
Added the same HACK as for WPP Settings page. Need to check and get feedback from users who had this issue.
