### ISSUE TITLE
XMLI. issue with reverse order of images

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#68]
Featured image is also the last
https://usabilitydynamics.com/products/wp-property/forum/topic/slideshow-image-order/

Note from user, 
We are having an issue where the slideshow images on each properties page is shown in reverse order. On the backend, the order is correct. (see screenshot: http://s28.postimg.org/ws0nfrnx9/slideshow_order.jpg).

To fix this, for some reason if I click “Auto Fix” above the “All Images” area, and then update the property, it will then sort them correctly. (See here: http://s18.postimg.org/jxze0q1ll/slideshow_order2.jpg).

**Comment by pemaxim** [comment]
Fixed.
