### ISSUE TITLE
PDF flyer. Not good look.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#69]
http://screencast.com/t/PSqLbIwhm
http://screencast.com/t/BI24xlYc
Empty spaces - http://screencast.com/t/dkMlI7Tz
Why the second page is showing - http://screencast.com/t/Iz1mdjECc9Q

**Comment by pemaxim** [comment]
It can not be fixed with the current implementation.
But client can configure it so it will be fine ( set 3 or less secondary images, set less details, etc ).

**Comment by pemaxim** [comment]
Update: pdf was being broken if image file name was not acceptable and image was not found because of it. Fixed now.
