### ISSUE TITLE
PDF. Attributes which have format checkboxes do not show on PDF

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#71]
Such Attributes which have format checkboxes do not show on PDF, enabled do not chow value. disabled do not show at all.

Property - http://screencast.com/t/oTtcuY2z00K

PDF - http://screencast.com/t/vtdA7aL4vr

**Comment by pemaxim** [comment]
I can not replicate the issue. 
It shows 'Yes' or 'No' values for checkboxes.
Please, give more details. Thanks.

**Comment by Mashenka** [comment]
I have sent you my wp-property configuration. Try to replicate with it.

**Comment by pemaxim** [comment]
Found the reason. It happened when 'Show Checkboxed Image instead of "Yes" and hide "No" for Yes/No values' option was enabled for Property page section
http://screencast.com/t/LrEZaYum0frI
Fixed.
