### ISSUE TITLE
PDF. Use not the latest PDF, after regenaration

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#73]
When you regenarating PDF flyers, functionality renew(delete old and past new) only for that ones which were created in current month. 

It generates new flyers for all properties, but pdf which were created before current month do not updated, functionality just create new one for them in current month folder, but using the old one pdf in [property_flyer].

https://usabilitydynamics.com/products/wp-property/forum/topic/pdf-flyers-generating-differently-not-uniform-across-the-board-1/?#post-26280

**Comment by pemaxim** [comment]
Fixed
