### ISSUE TITLE
First time when you try to upload wp-property configuration on fresh plugin in php5.5

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#88]
If Power Tools installed:

PHP Warning:  Invalid argument supplied for foreach() in .....wp-content/plugins/wp-property/core/premium/class_wpp_power_tools.php on line 131, referer: ...../wordpress/wp-admin/edit.php?post_type=property&page=property_settings

So the settings page just freezes. After second try it successfully saves settings.

**Comment by pemaxim** [comment]
Fixed
