### ISSUE TITLE
Supermap.

### ISSUE THREAD

**Issue by Mashenka** [wp-property/wp-property#89]
https://usabilitydynamics.com/products/wp-property/forum/topic/1-36-3-fixed-fancybox-on-supermaps-infobox-is-not-working-on-version-1-41-4/?#post-26673

**Comment by pemaxim** [comment]
I can not replicate the issue. It works for me.

**Comment by pemaxim** [comment]
Tested in Denali and TwentyTwelve themes

**Comment by Mashenka** [comment]
And I can replicate on Denali theme even if option "Show larger image of Property when image is clicked using fancybox." enabled.
